### ISSUE TITLE
Uncaught TypeError: Cannot read property 'shift' of undefined [$15]

### ISSUE THREAD

**Issue by kelkes** [emmetio/emmet-atom#172]
Uncaught TypeError: Cannot read property 'shift' of undefined

**Atom Version**: 0.156.0
**System**: Mac OS X 10.10.1
**Thrown From**: [emmet](https://github.com/emmetio/emmet-atom) package, v2.2.1
### Steps To Reproduce
1. ...
2. ...
### Stack Trace

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:121

TypeError: Cannot read property 'shift' of undefined
  at Object.locateRule (/Users/dwippel/.atom/packages/emmet/node_modules/emmet/lib/utils/cssSections.js:416:42)
  at Object.parseFromPosition (/Users/dwippel/.atom/packages/emmet/node_modules/emmet/lib/editTree/css.js:564:29)
  at Object.propertyFromPosition (/Users/dwippel/.atom/packages/emmet/node_modules/emmet/lib/editTree/css.js:584:41)
  at Object.module.exports.gradientsFromCSSProperty (/Users/dwippel/.atom/packages/emmet/node_modules/emmet/lib/resolver/cssGradient.js:333:30)
  at Object.module.exports.expandAbbreviationHandler (/Users/dwippel/.atom/packages/emmet/node_modules/emmet/lib/resolver/cssGradient.js:363:25)
  at Object.bound [as fn] (/Users/dwippel/.atom/packages/emmet/node_modules/emmet/node_modules/lodash/lodash.js:622:21)
  at /Users/dwippel/.atom/packages/emmet/node_modules/emmet/lib/assets/handlerList.js:80:19
  at Function.find (/Users/dwippel/.atom/packages/emmet/node_modules/emmet/node_modules/lodash/lodash.js:3109:15)
  at Object.HandlerList.exec (/Users/dwippel/.atom/packages/emmet/node_modules/emmet/lib/assets/handlerList.js:79:6)
  at Object.expandAbbreviationAction (/Users/dwippel/.atom/packages/emmet/node_modules/emmet/lib/action/expandAbbreviation.js:111:20)
  at Object.expandAbbreviationWithTabAction (/Users/dwippel/.atom/packages/emmet/node_modules/emmet/lib/action/expandAbbreviation.js:141:14)
  at Object.bound [as fn] (/Users/dwippel/.atom/packages/emmet/node_modules/emmet/node_modules/lodash/lodash.js:622:21)
  at Object.run (/Users/dwippel/.atom/packages/emmet/node_modules/emmet/lib/action/main.js:151:21)
  at Object.run (/Users/dwippel/.atom/packages/emmet/node_modules/emmet/lib/emmet.js:91:23)
  at runAction (/Users/dwippel/.atom/packages/emmet/lib/emmet.coffee:77:9)
  at /Users/dwippel/.atom/packages/emmet/lib/emmet.coffee:45:9
  at Object.module.exports.exec (/Users/dwippel/.atom/packages/emmet/lib/editor-proxy.coffee:78:10)
  at /Users/dwippel/.atom/packages/emmet/lib/emmet.coffee:44:19
  at History.module.exports.History.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:112:18)
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:683:27)
  at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1146:26)
  at /Users/dwippel/.atom/packages/emmet/lib/emmet.coffee:43:24
  at atom-text-editor.<anonymous> (/Users/dwippel/.atom/packages/emmet/lib/emmet.coffee:132:15)
  at atom-text-editor.handler (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:115:32)
  at atom-text-editor.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at atom-text-editor.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:549:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:391:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:167:20)

```

/cc @atom/core
##

**Comment by MozMorris** [comment]
This is still present in v2.3.0.

## Steps to reproduce

Top of CSS file looks like this:

    /*------------------------------------*\
    $INDENT ME
    \*------------------------------------*/

1. Try to indent `$INDENT ME` using `tab`. Error is thrown.

**Comment by MarioGiancini** [comment]
Same here, top of CSS file.

Used SHIFT + ] on highlighted text as work around.

**Comment by adamkdean** [comment]
I'm also getting this issue with a header that is:

/* Example: text
 * Example: text
 */

**Comment by vegetableman** [comment]
@sergeche Have submitted a patch https://github.com/emmetio/emmet/pull/374 which should fix this.
