### ISSUE TITLE
Uncaught TypeError: Cannot read property 'shift' of undefined

### ISSUE THREAD

**Issue by radmanesh** [emmetio/emmet-atom#188]
[Enter steps to reproduce below:]

1. Type: /*comment*/
2. Move the cursor somewhere in the comment and press Tab.

**Atom Version**: 0.165.0
**System**: Mac OS X 10.10.1
**Thrown From**: [emmet](https://github.com/emmetio/emmet-atom) package, v2.2.1

### Stack Trace

Uncaught TypeError: Cannot read property 'shift' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:121

TypeError: Cannot read property 'shift' of undefined
  at Object.locateRule (/Users/arman/.atom/packages/emmet/node_modules/emmet/lib/utils/cssSections.js:416:42)
  at Object.parseFromPosition (/Users/arman/.atom/packages/emmet/node_modules/emmet/lib/editTree/css.js:564:29)
  at Object.propertyFromPosition (/Users/arman/.atom/packages/emmet/node_modules/emmet/lib/editTree/css.js:584:41)
  at Object.module.exports.gradientsFromCSSProperty (/Users/arman/.atom/packages/emmet/node_modules/emmet/lib/resolver/cssGradient.js:333:30)
  at Object.module.exports.expandAbbreviationHandler (/Users/arman/.atom/packages/emmet/node_modules/emmet/lib/resolver/cssGradient.js:363:25)
  at Object.bound [as fn] (/Users/arman/.atom/packages/emmet/node_modules/emmet/node_modules/lodash/lodash.js:622:21)
  at /Users/arman/.atom/packages/emmet/node_modules/emmet/lib/assets/handlerList.js:80:19
  at Function.find (/Users/arman/.atom/packages/emmet/node_modules/emmet/node_modules/lodash/lodash.js:3109:15)
  at Object.HandlerList.exec (/Users/arman/.atom/packages/emmet/node_modules/emmet/lib/assets/handlerList.js:79:6)
  at Object.expandAbbreviationAction (/Users/arman/.atom/packages/emmet/node_modules/emmet/lib/action/expandAbbreviation.js:111:20)
  at Object.expandAbbreviationWithTabAction (/Users/arman/.atom/packages/emmet/node_modules/emmet/lib/action/expandAbbreviation.js:141:14)
  at Object.bound [as fn] (/Users/arman/.atom/packages/emmet/node_modules/emmet/node_modules/lodash/lodash.js:622:21)
  at Object.run (/Users/arman/.atom/packages/emmet/node_modules/emmet/lib/action/main.js:151:21)
  at Object.run (/Users/arman/.atom/packages/emmet/node_modules/emmet/lib/emmet.js:91:23)
  at runAction (/Users/arman/.atom/packages/emmet/lib/emmet.coffee:77:9)
  at /Users/arman/.atom/packages/emmet/lib/emmet.coffee:45:9
  at Object.module.exports.exec (/Users/arman/.atom/packages/emmet/lib/editor-proxy.coffee:78:10)
  at /Users/arman/.atom/packages/emmet/lib/emmet.coffee:44:19
  at History.module.exports.History.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:112:18)
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:683:27)
  at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1146:26)
  at /Users/arman/.atom/packages/emmet/lib/emmet.coffee:43:24
  at atom-text-editor.<anonymous> (/Users/arman/.atom/packages/emmet/lib/emmet.coffee:132:15)
  at atom-text-editor.handler (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:115:32)
  at atom-text-editor.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at atom-text-editor.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:549:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:391:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:167:20)

```

### Commands

```
  2x -30:24.9 core:move-left (input.hidden-input)
     -30:23.7 editor:move-to-end-of-screen-line (input.hidden-input)
     -30:23.3 emmet:insert-formatted-line-break-only (input.hidden-input)
     -30:23.3 editor:newline (input.hidden-input)
     -30:19.2 editor:select-to-first-character-of-line (input.hidden-input)
  2x -30:18.7 core:backspace (input.hidden-input)
     -30:17.6 core:move-up (input.hidden-input)
     -30:16.8 editor:select-to-first-character-of-line (input.hidden-input)
  2x -30:16.4 core:backspace (input.hidden-input)
     -30:15.1 core:move-down (input.hidden-input)
     -30:14.7 editor:move-to-first-character-of-line (input.hidden-input)
  2x -30:14.0 core:move-right (input.hidden-input)
     -30:12.4 core:backspace (input.hidden-input)
  2x -30:12.2 emmet:expand-abbreviation-with-tab (input.hidden-input)
     -30:04.6 core:save (input.hidden-input)
     -30:00.0 emmet:expand-abbreviation-with-tab (input.hidden-input)
```

### Config

```
{
  "core": {
    "themes": [
      "atom-light-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
bootstrap-3-snippetset, v0.0.6
color-picker, v1.2.6
dash, v1.0.0
emmet, v2.2.1
linter, v0.7.4
linter-jsl, v0.0.1
linter-tidy, v0.0.1
minimap, v3.3.13

# Dev
No dev packages
```

/cc @atom/core

**Comment by MozMorris** [comment]
Pretty sure this is the same as #172

**Comment by wesleycoder** [comment]
This errors occurs also with the following steps:
- create an **html** file
- type `!` and hit *tab*
- create a `<style>` tag in head
- split the tag in two lines
- enter any style like:
```
body{
}
```
- go right after the opening `<style>` tag and hit *enter*
- hit *tab*
- > Now the error explodes!

**Comment by yumitsu** [comment]
Also occurs in **scss** files when pressing *tab* on newline in `/** **/` comment block.

**Comment by JulianKingman** [comment]
Also happens in **less** when I hit *tab* on @import

**Comment by PaulMorel** [comment]
To add to what @JulianKingman reported, it also happens when I hit <kbd>Tab</kbd> on a variable in a LESS file.

**Comment by equinusocio** [comment]
Up for this. Very annoying bug.

**Comment by sergeche** [comment]
Should be fixed in v2.3.9

**Comment by PaulMorel** [comment]
No more problems on v2.3.9. Thanks

**Comment by samsch** [comment]
I'm getting this error in v2.3.9 by hitting tab on a blank line in a SCSS file. It happens only before any braces '{' in the file.
