### ISSUE TITLE
Can't install - Request for package information failed

### ISSUE THREAD

**Issue by Pixxel** [emmetio/emmet-atom#203]
Latest version of Atom and Emmet.

`Installing “emmet-atom@2.3.2” failed.Hide output…
Request for package information failed: Not Found`

Console:

`Installing package emmet-atom failed Error: Installing “emmet-atom@2.3.2” failed.
  at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:280:21
  at exit (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:63:47)
  at /Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:70:18
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:150:18)
  at Socket.emit (events.js:129:20)
  at Pipe.close (net.js:469:12)
 Request for package information failed: Not Found`

**Comment by sergeche** [comment]
It looks like a temporary issue with package registry or Atom itself
