### ISSUE TITLE
Uncaught ParseError: CSS parsing error at line 1, char 19: Unrecognized character '´'background-image: ´;------------------^

### ISSUE THREAD

**Issue by rafaelgom3s** [emmetio/emmet-atom#224]
How to reproduce
1. Typed character "´"
2. tried auto-complete (pressing ctrl+space) and the following error occured

**Atom Version**: 0.184.0
**System**: Mac OS X 10.10.2
**Thrown From**: [emmet](https://github.com/emmetio/emmet-atom) package, v2.3.4
### Stack Trace

Uncaught ParseError: CSS parsing error at line 1, char 19: Unrecognized character '´'
background-image: ´;
------------------^

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:124

ParseError: CSS parsing error at line 1, char 19: Unrecognized character '´'
background-image: ´;
------------------^
  at raiseError (/Users/rafa/.atom/packages/emmet/node_modules/emmet/lib/parser/css.js:111:16)
  at tokenize (/Users/rafa/.atom/packages/emmet/node_modules/emmet/lib/parser/css.js:369:3)
  at Object.lex (/Users/rafa/.atom/packages/emmet/node_modules/emmet/lib/parser/css.js:387:6)
  at Object.parse (/Users/rafa/.atom/packages/emmet/node_modules/emmet/lib/parser/css.js:405:22)
  at extractPropertiesFromSource (/Users/rafa/.atom/packages/emmet/node_modules/emmet/lib/editTree/css.js:246:26)
  at consumeProperties (/Users/rafa/.atom/packages/emmet/node_modules/emmet/lib/editTree/css.js:217:14)
  at [object Object].editTree.EditContainer.extend.initialize (/Users/rafa/.atom/packages/emmet/node_modules/emmet/lib/editTree/css.js:316:4)
  at [object Object].EditContainer (/Users/rafa/.atom/packages/emmet/node_modules/emmet/lib/editTree/base.js:66:19)
  at new child (/Users/rafa/.atom/packages/emmet/node_modules/emmet/lib/vendor/klass.js:35:12)
  at Object.parse (/Users/rafa/.atom/packages/emmet/node_modules/emmet/lib/editTree/css.js:550:11)
  at Object.parseFromPosition (/Users/rafa/.atom/packages/emmet/node_modules/emmet/lib/editTree/css.js:566:16)
  at Object.propertyFromPosition (/Users/rafa/.atom/packages/emmet/node_modules/emmet/lib/editTree/css.js:580:49)
  at Object.module.exports.gradientsFromCSSProperty (/Users/rafa/.atom/packages/emmet/node_modules/emmet/lib/resolver/cssGradient.js:335:30)
  at Object.module.exports.expandGradientOutsideValue (/Users/rafa/.atom/packages/emmet/node_modules/emmet/lib/resolver/cssGradient.js:443:25)
  at Object.module.exports.expandAbbreviationHandler (/Users/rafa/.atom/packages/emmet/node_modules/emmet/lib/resolver/cssGradient.js:408:16)
  at /Users/rafa/.atom/packages/emmet/node_modules/emmet/lib/assets/handlerList.js:93:19
  at /Users/rafa/.atom/packages/emmet/node_modules/emmet/lib/utils/common.js:600:10
  at Array.some (native)
  at Object.find (/Users/rafa/.atom/packages/emmet/node_modules/emmet/lib/utils/common.js:599:9)
  at Object.HandlerList.exec (/Users/rafa/.atom/packages/emmet/node_modules/emmet/lib/assets/handlerList.js:92:10)
  at Object.expandAbbreviationAction (/Users/rafa/.atom/packages/emmet/node_modules/emmet/lib/action/expandAbbreviation.js:110:20)
  at Object.expandAbbreviationWithTabAction (/Users/rafa/.atom/packages/emmet/node_modules/emmet/lib/action/expandAbbreviation.js:140:14)
  at Object.run (/Users/rafa/.atom/packages/emmet/node_modules/emmet/lib/action/main.js:150:21)
  at Object.run (/Users/rafa/.atom/packages/emmet/node_modules/emmet/lib/emmet.js:81:23)
  at runAction (/Users/rafa/.atom/packages/emmet/lib/emmet.coffee:91:9)
  at /Users/rafa/.atom/packages/emmet/lib/emmet.coffee:59:9
  at Object.module.exports.exec (/Users/rafa/.atom/packages/emmet/lib/editor-proxy.coffee:80:10)
  at /Users/rafa/.atom/packages/emmet/lib/emmet.coffee:58:19
  at History.module.exports.History.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:115:18)
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:687:27)
  at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1209:26)
  at atom-text-editor.<anonymous> (/Users/rafa/.atom/packages/emmet/lib/emmet.coffee:57:24)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:182:20)

```
### Commands

```
     -0:12.0 autocomplete:toggle (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:10.9 core:move-down (atom-text-editor.editor.mini)
     -0:10.5 core:confirm (atom-text-editor.editor.mini)
     -0:09.8 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:08.3 emmet:expand-abbreviation-with-tab (atom-text-editor.editor.is-focused.autocomplete-active)
  3x -0:07.7 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:05.8 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:05.8 editor:newline (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:05.3 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:04.9 editor:delete-to-beginning-of-line (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:02.5 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:02.5 editor:newline (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:02.1 emmet:expand-abbreviation-with-tab (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:01.2 editor:consolidate-selections (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:01.2 core:cancel (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:00.4 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "language-php",
      "language-perl"
    ],
    "themes": [
      "graphite-ui",
      "seti-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
autocomplete-css, v0.3.0
autocomplete-html, v0.2.0
autocomplete-plus, v2.3.0
autocomplete-ruby, v0.0.1
color-picker, v1.4.4
emmet, v2.3.4
file-icons, v1.5.0
graphite-ui, v0.14.1
ionic-atom, v0.3.1
language-coffee-script-angular, v2.2.0
language-gitignore, v0.1.1
language-haml, v0.15.0
language-jade, v0.3.0
linter, v0.12.0
linter-coffeelint, v0.1.7
minimap, v4.4.0
seti-syntax, v0.3.3

# Dev
No dev packages
```
##

**Comment by silvenon** [comment]
Enter steps to reproduce, as the beginning of your message suggests :smiley:

**Comment by MethodGrab** [comment]
Atom: 1.0.2
emmet-atom: 2.3.12

This seems to be the first report of this issue, duplicated by #229, #267, #287, #307, so I'll post my findings here.

Steps to reproduce:
1. Open a new file
2. Change the syntax to CSS/SCSS
3. Type one of the following characters: ` ±
4. Press `tab` to trigger `emmet:expand-abbreviation-with-tab`
5. Observe the error mentioned above (shows as a popup and the same error in the console).
