### ISSUE TITLE
Failed to activate the emmet package

### ISSUE THREAD

**Issue by JLevstein** [emmetio/emmet-atom#230]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.187.0
**System**: Mac OS X 10.10.2
**Thrown From**: [emmet](https://github.com/emmetio/emmet-atom) package, v2.3.4

### Stack Trace

Failed to activate the emmet package

```
At ENOENT, no such file or directory 
'/.atom/packages/emmet/vendor/snippets.json'

Error: ENOENT, no such file or directory 
'/.atom/packages/emmet/vendor/snippets.json'
  at Error (native)
  at Object.fs.openSync (fs.js:503:18)
  at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:118:20)
  at Object.fs.readFileSync (fs.js:355:15)
  at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:362:29)
  at Object.module.exports.setupSnippets (/Users/jonathanlevstein/.atom/packages/emmet/lib/emmet.coffee:63:3)
  at Object.module.exports.activate (/Users/jonathanlevstein/.atom/packages/emmet/lib/emmet.coffee:34:7)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:240:19)
  at /Applications/Atom.app/Contents/Resources/app/src/package.js:221:30
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:167:15)
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:214:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:465:21)
  at /Applications/Atom.app/Contents/Resources/app/src/package-manager.js:334:19
  at /Applications/Atom.app/Contents/Resources/app/src/config.js:640:20
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Config.module.exports.Config.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app/src/config.js:804:29)
  at Config.module.exports.Config.setRawValue (/Applications/Atom.app/Contents/Resources/app/src/config.js:617:19)
  at Config.module.exports.Config.set (/Applications/Atom.app/Contents/Resources/app/src/config.js:231:14)
  at Config.module.exports.Config.removeAtKeyPath (/Applications/Atom.app/Contents/Resources/app/src/config.js:409:12)
  at Package.module.exports.Package.enable (/Applications/Atom.app/Contents/Resources/app/src/package.js:152:26)
  at PackageManager.module.exports.PackageManager.enablePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:162:14)
  at HTMLButtonElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-card.js:209:27)
  at HTMLButtonElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:4430:9)
  at HTMLButtonElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:4116:28)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "neutron-ui",
      "tomorrow-night-eighties"
    ],
    "disabledPackages": [
      "whitespace"
    ],
    "audioBeep": false
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v1.4.4
editor-stats, v0.17.0
emmet, v2.3.4
neutron-ui, v0.3.0
tomorrow-night-eighties, v0.4.0
vim-mode, v0.36.0

# Dev
No dev packages
```

**Comment by gavinwye** [comment]
@JLevstein did you close this issue because it's resolved? I'm having the same issue in version 1.187.0

**Comment by JLevstein** [comment]
@gavinwye Not fully, but I don't seem to get the error anymore when I disable and re-enable it. Emmet was also working fine after getting this error the first time.

I was also just messing around a bit with the auto-issue reporting because I hadn't seen it before. Sorry for the confusion!

**Comment by gavinwye** [comment]
@JLevstein ahh okay. Yea the quto-issue reporting is neat.

I've restarted Atom and the problem seems to have gone away :)

**Comment by maenotsuzuki** [comment]
I've restarted Atom and the problem still persists

**Comment by mostafaAswany** [comment]
I have entered the packege and found 2 emmet packege ,i remove  them and install 1 emmet packege again and the problem solved.

**Comment by Lesya13** [comment]
and I have this problem :(

**Comment by githubSathishkumar** [comment]
I'm too faced the same issue in latest version of the package

**Comment by mohas777** [comment]
just go to your packages and uninstall one emmet in the packages. just found I had two emmet installed in my packages and uninstalled one. problem solved

**Comment by azikolmn** [comment]
who knows what i must do in this problem

**Comment by PA55ION** [comment]
yep I have the same issue

**Comment by 3otes** [comment]
Same problem here, after loading as part of Udacity's ways to help code faster got this error:

Failed to activate the emmet package
Cannot find module 'emmet'
Hide Stack Trace
Error: Cannot find module 'emmet'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (C:\Users\FANIE\AppData\Local\atom\app-1.27.1\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (C:\Users\FANIE\AppData\Local\atom\app-1.27.1\resources\app\src\module-cache.js:354:58)
    at Module.require (file:///C:/Users/FANIE/AppData/Local/atom/app-1.27.1/resources/app.asar/static/index.js:40:43)
    at require (C:\Users\FANIE\AppData\Local\atom\app-1.27.1\resources\app\src\native-compile-cache.js:66:33)
    at Object.<anonymous> (file:///C:/Users/FANIE/.atom/packages/emmet/lib/emmet.coffee:5:9)
    at Object.<anonymous> (file:///C:/Users/FANIE/.atom/packages/emmet/lib/emmet.coffee:1:1)
    at Object.<anonymous> (file:///C:/Users/FANIE/.atom/packages/emmet/lib/emmet.coffee:1:1)
    at Module.get_Module._compile (C:\Users\FANIE\AppData\Local\atom\app-1.27.1\resources\app\src\native-compile-cache.js:106:36)
    at Object.value [as .coffee] (C:\Users\FANIE\AppData\Local\atom\app-1.27.1\resources\app\src\compile-cache.js:240:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (file:///C:/Users/FANIE/AppData/Local/atom/app-1.27.1/resources/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (C:\Users\FANIE\AppData\Local\atom\app-1.27.1\resources\app\static\<embedded>:96:26)
    at Package.requireMainModule (C:\Users\FANIE\AppData\Local\atom\app-1.27.1\resources\app\src\package.js:782:33)
    at Package.activateNow (C:\Users\FANIE\AppData\Local\atom\app-1.27.1\resources\app\src\package.js:220:40)
    at measure (C:\Users\FANIE\AppData\Local\atom\app-1.27.1\resources\app\src\package.js:206:33)
    at Package.measure (C:\Users\FANIE\AppData\Local\atom\app-1.27.1\resources\app\src\package.js:88:25)
    at activationPromise.Promise (C:\Users\FANIE\AppData\Local\atom\app-1.27.1\resources\app\src\package.js:200:20)
    at Promise (<anonymous>)
    at Package.activate (C:\Users\FANIE\AppData\Local\atom\app-1.27.1\resources\app\src\package.js:198:38)
    at PackageManager.activatePackage (C:\Users\FANIE\AppData\Local\atom\app-1.27.1\resources\app\src\package-manager.js:695:42)
    at config.transactAsync (C:\Users\FANIE\AppData\Local\atom\app-1.27.1\resources\app\src\package-manager.js:670:36)
    at Config.transactAsync (C:\Users\FANIE\AppData\Local\atom\app-1.27.1\resources\app\src\config.js:866:28)
    at PackageManager.activatePackages (C:\Users\FANIE\AppData\Local\atom\app-1.27.1\resources\app\src\package-manager.js:668:23)
    at PackageManager.activate (C:\Users\FANIE\AppData\Local\atom\app-1.27.1\resources\app\src\package-manager.js:647:50)
    at loadStatePromise.loadState.then (C:\Users\FANIE\AppData\Local\atom\app-1.27.1\resources\app\src\atom-environment.js:871:27)
    at <anonymous>
The error was thrown from the emmet package. This issue has already been reported.
View Issue
