### ISSUE TITLE
Failed to load the emmet-atom package

### ISSUE THREAD

**Issue by kalyco** [emmetio/emmet-atom#238]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.187.0
**System**: Mac OS X 10.10.2
**Thrown From**: [emmet](https://github.com/emmetio/emmet-atom) package, v2.3.4

### Stack Trace

Failed to load the emmet-atom package

```
At Cannot find module 'emmet'

Error: Cannot find module 'emmet'
    at Module._resolveFilename (module.js:351:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:383:52)
    at Function.Module._load (module.js:293:25)
    at Module.require (module.js:380:17)
    at require (module.js:399:17)
    at Object.<anonymous> (/Users/Kayla/.atom/packages/emmet/lib/emmet.coffee:8:11)
    at Object.<anonymous> (/Users/Kayla/.atom/packages/emmet/lib/emmet.coffee:188:4)
    at Module._compile (module.js:475:26)
    at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
    at Module.load (module.js:370:32)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai"
    ]
  },
  "emmet": {}
}
```

### Installed Packages

```coffee
# User
emmet, v2.3.4
emmet-atom, v2.3.0
file-icons, v1.4.5
linter, v0.10.1
linter-ruby, v0.1.4
monokai, v0.12.0

# Dev
No dev packages
```

**Comment by sergeche** [comment]
Why did you installed `emmet` package? You should only install `emmet-atom`

**Comment by sergeche** [comment]
And it looks like you simply copied package source instead of installing it via Package Manager
