### ISSUE TITLE
Uncaught Error: Invalid abbreviation

### ISSUE THREAD

**Issue by StumblinGrumblin** [emmetio/emmet-atom#239]
[Enter steps to reproduce below:]

1. ...input*3[ng-model="ctrl."]
2. ...Ctrl+E to trigger snippet

**Atom Version**: 0.188.0
**System**: Mac OS X 10.10.2
**Thrown From**: [emmet](https://github.com/emmetio/emmet-atom) package, v2.3.4

### Stack Trace

Uncaught Error: Invalid abbreviation

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:128

Error: Invalid abbreviation
    at Object.AbbreviationNode.setAbbreviation (/Users/stumblingrumblin/.atom/packages/emmet/node_modules/emmet/lib/parser/abbreviation.js:344:11)
    at parseAbbreviation (/Users/stumblingrumblin/.atom/packages/emmet/node_modules/emmet/lib/parser/abbreviation.js:560:14)
    at Object.parse (/Users/stumblingrumblin/.atom/packages/emmet/node_modules/emmet/lib/parser/abbreviation.js:890:15)
    at Object.expand (/Users/stumblingrumblin/.atom/packages/emmet/node_modules/emmet/lib/parser/abbreviation.js:957:26)
    at Object.handlers.add.order [as fn] (/Users/stumblingrumblin/.atom/packages/emmet/node_modules/emmet/lib/action/expandAbbreviation.js:65:25)
    at /Users/stumblingrumblin/.atom/packages/emmet/node_modules/emmet/lib/assets/handlerList.js:93:19
    at /Users/stumblingrumblin/.atom/packages/emmet/node_modules/emmet/lib/utils/common.js:600:10
    at Array.some (native)
    at Object.find (/Users/stumblingrumblin/.atom/packages/emmet/node_modules/emmet/lib/utils/common.js:599:9)
    at Object.HandlerList.exec (/Users/stumblingrumblin/.atom/packages/emmet/node_modules/emmet/lib/assets/handlerList.js:92:10)
```

### Commands

```
  3x -3:40.1 core:backspace (atom-text-editor.editor.is-focused)
     -1:23.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
     -1:10.6 editor:newline (atom-text-editor.editor.is-focused)
  2x -1:09.6 core:backspace (atom-text-editor.editor.is-focused)
  3x -0:53.4 core:move-right (atom-text-editor.editor.is-focused)
     -0:48.8 emmet:expand-abbreviation (atom-text-editor.editor.is-focused)
     -0:45.1 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:45.1 editor:newline (atom-text-editor.editor.is-focused)
     -0:44.4 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:44.4 editor:newline (atom-text-editor.editor.is-focused)
     -0:43.7 core:move-up (atom-text-editor.editor.is-focused)
  2x -0:08.9 core:move-right (atom-text-editor.editor.is-focused)
     -0:07.4 emmet:expand-abbreviation (atom-text-editor.editor.is-focused)
     -0:03.2 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:03.2 core:cancel (atom-text-editor.editor.is-focused)
     -0:01.0 emmet:expand-abbreviation (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter",
      "linter-erb",
      "linter-rubocop",
      "fancy-new-file"
    ],
    "themes": [
      "atom-dark-ui",
      "solarized-dark-syntax"
    ]
  },
  "emmet": {}
}
```

### Installed Packages

```coffee
# User
angularjs, v0.2.0
atom-beautify, v0.23.1
autocomplete-plus, v2.7.1
color-picker, v1.5.0
emmet, v2.3.4
file-icons, v1.5.2
linter-csslint, v0.0.11
linter-jshint, v0.1.0
linter-tidy, v1.0.0
minimap, v4.7.1
tabs-to-spaces, v0.9.2

# Dev
No dev packages
```

**Comment by sergeche** [comment]
`input[ng-model="ctrl."]*3`

**Comment by damionp3000** [comment]
Hello,

Just wanted to present what I noticed. We are both using the atom-dark-ui syntax. Not sure if that helps, but one thing that may be a  close relation.

**Comment by 373skn** [comment]
Same happens in Atom 1.7.1 Mac 10.11.3

`table>tr*6>td*7{$}|c`

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.1
**System**: Mac OS X 10.11.3
**Thrown From**: [emmet](https://github.com/emmetio/emmet-atom) package, v2.4.3


### Stack Trace

Uncaught Error: Invalid abbreviation

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:833

Error: Invalid abbreviation
    at Object.AbbreviationNode.setAbbreviation (/Users/sekinominami/.atom/packages/emmet/node_modules/emmet/lib/parser/abbreviation.js:344:11)
    at parseAbbreviation (/Users/sekinominami/.atom/packages/emmet/node_modules/emmet/lib/parser/abbreviation.js:560:14)
    at Object.parse (/Users/sekinominami/.atom/packages/emmet/node_modules/emmet/lib/parser/abbreviation.js:890:15)
    at Object.expand (/Users/sekinominami/.atom/packages/emmet/node_modules/emmet/lib/parser/abbreviation.js:957:26)
    at Object.handlers.add.order [as fn] (/Users/sekinominami/.atom/packages/emmet/node_modules/emmet/lib/action/expandAbbreviation.js:65:25)
    at /Users/sekinominami/.atom/packages/emmet/node_modules/emmet/lib/assets/handlerList.js:93:19
    at /Users/sekinominami/.atom/packages/emmet/node_modules/emmet/lib/utils/common.js:600:10
    at Array.some (native)
    at Object.find (/Users/sekinominami/.atom/packages/emmet/node_modules/emmet/lib/utils/common.js:599:9)
    at Object.HandlerList.exec (/Users/sekinominami/.atom/packages/emmet/node_modules/emmet/lib/assets/handlerList.js:92:10)
    at Object.expandAbbreviationAction (/Users/sekinominami/.atom/packages/emmet/node_modules/emmet/lib/action/expandAbbreviation.js:110:20)
    at Object.run (/Users/sekinominami/.atom/packages/emmet/node_modules/emmet/lib/action/main.js:150:21)
    at Object.run (/Users/sekinominami/.atom/packages/emmet/node_modules/emmet/lib/emmet.js:81:23)
    at runAction (/Users/sekinominami/.atom/packages/emmet/lib/emmet.coffee:94:9)
    at /Users/sekinominami/.atom/packages/emmet/lib/emmet.coffee:62:9
    at Object.module.exports.exec (/Users/sekinominami/.atom/packages/emmet/lib/editor-proxy.coffee:80:10)
    at /Users/sekinominami/.atom/packages/emmet/lib/emmet.coffee:61:19
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:828:18)
    at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1274:26)
    at atom-text-editor.<anonymous> (/Users/sekinominami/.atom/packages/emmet/lib/emmet.coffee:60:24)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
  4x -4:19.4.0 core:move-right (atom-text-editor.editor.is-focused)
     -3:58.9.0 emmet:expand-abbreviation-with-tab (atom-text-editor.editor.is-focused.autocomplete-active)
  5x -2:30.9.0 core:move-right (atom-text-editor.editor.is-focused)
     -2:26.6.0 emmet:expand-abbreviation-with-tab (atom-text-editor.editor.is-focused)
     -2:19 core:backspace (atom-text-editor.editor.is-focused)
     -2:18.3.0 core:move-left (atom-text-editor.editor.is-focused)
  3x -2:18 core:select-right (atom-text-editor.editor.is-focused)
     -2:16.9.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -2:16.5.0 core:move-right (atom-text-editor.editor.is-focused)
     -2:15.9.0 emmet:expand-abbreviation-with-tab (atom-text-editor.editor.is-focused)
     -2:13.3.0 core:undo (atom-text-editor.editor.is-focused)
  2x -2:11 core:move-left (atom-text-editor.editor.is-focused)
  3x -1:58 core:move-right (atom-text-editor.editor.is-focused)
     -1:57.3.0 emmet:expand-abbreviation-with-tab (atom-text-editor.editor.is-focused)
  7x -1:47.9.0 core:undo (atom-text-editor.editor.is-focused)
     -0:00.7.0 emmet:expand-abbreviation (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "allowPendingPaneItems": false,
    "audioBeep": false,
    "openEmptyEditorOnStart": false
  },
  "emmet": {}
}
```

### Installed Packages

```coffee
# User
Remote-FTP, v0.7.20
atom-html-preview, v0.1.19
autocomplete-paths, v1.0.2
color-picker, v2.1.1
emmet, v2.4.3
file-icons, v1.7.4
japanese-menu, v1.7.0
minimap, vundefined
minimap-autohide, v0.10.1
pigments, v0.26.0

# Dev
No dev packages
```

**Comment by cristian-sima** [comment]
Same error for 

`thead>tr>td*6{0}`

**Comment by sergeche** [comment]
@cristian-sima `thead>tr>td{0}*6`

**Comment by apodworny** [comment]
I got this error by trying to do tr*5td*5 (which is wrong), instead do something like tr*5>td*4

**Comment by rcdosado** [comment]
i'm getting Uncaught Error : Invalid Abbreviation after typing ctrl+e on `span>li*5{}`

**Comment by iamRockinRobin** [comment]
@rcdosado I got the same error but found a work-around (that got rid of the error and output the correct code) by putting the "greater than" symbol after the 5:
span>li*5>{}

**Comment by rcdosado** [comment]
@iamRockinRobin Thanks for the workaround..

**Comment by cristian-sima** [comment]
For this code

```
table.table.table-reflow>thead>tr>th*2{{''}}
```

and then `TAB`

**Comment by kerhong** [comment]
Atom: 1.10.2
Emmet: 2.4.3

Empty file with language set to HTML.
`|` (vertical line) `emmet:expand-abbreviation`

```/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:873
Hide Stack Trace
Error: Invalid abbreviation
    at Object.AbbreviationNode.setAbbreviation (/home/myusername/.atom/packages/emmet/node_modules/emmet/lib/parser/abbreviation.js:344:11)
    at parseAbbreviation (/home/myusername/.atom/packages/emmet/node_modules/emmet/lib/parser/abbreviation.js:560:14)
    at Object.parse (/home/myusername/.atom/packages/emmet/node_modules/emmet/lib/parser/abbreviation.js:890:15)
    at Object.expand (/home/myusername/.atom/packages/emmet/node_modules/emmet/lib/parser/abbreviation.js:957:26)
    at Object.handlers.add.order [as fn] (/home/myusername/.atom/packages/emmet/node_modules/emmet/lib/action/expandAbbreviation.js:65:25)
    at /home/myusername/.atom/packages/emmet/node_modules/emmet/lib/assets/handlerList.js:93:19
    at /home/myusername/.atom/packages/emmet/node_modules/emmet/lib/utils/common.js:600:10
    at Array.some (native)
    at Object.find (/home/myusername/.atom/packages/emmet/node_modules/emmet/lib/utils/common.js:599:9)
    at Object.HandlerList.exec (/home/myusername/.atom/packages/emmet/node_modules/emmet/lib/assets/handlerList.js:92:10)
    at Object.expandAbbreviationAction (/home/myusername/.atom/packages/emmet/node_modules/emmet/lib/action/expandAbbreviation.js:110:20)
    at Object.run (/home/myusername/.atom/packages/emmet/node_modules/emmet/lib/action/main.js:150:21)
    at Object.run (/home/myusername/.atom/packages/emmet/node_modules/emmet/lib/emmet.js:81:23)
    at runAction (/home/myusername/.atom/packages/emmet/lib/emmet.coffee:94:9)
    at /home/myusername/.atom/packages/emmet/lib/emmet.coffee:62:9
    at Object.module.exports.exec (/home/myusername/.atom/packages/emmet/lib/editor-proxy.coffee:80:10)
    at /home/myusername/.atom/packages/emmet/lib/emmet.coffee:61:19
    at TextBuffer.module.exports.TextBuffer.transact (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:868:18)
    at TextEditor.module.exports.TextEditor.transact (/usr/share/atom/resources/app.asar/src/text-editor.js:1402:26)
    at atom-text-editor.<anonymous> (/home/myusername/.atom/packages/emmet/lib/emmet.coffee:60:24)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/usr/share/atom/resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:183:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)```

**Comment by M-Raslan** [comment]
I had the same error it only happens when i tried to assign value to li 
    .content>h1{Hello!}+.nav>ul>li*4{test}
when i tried 
.content>h1{Hello!}+.nav>ul>li*4>a[href="#"] it runs very well with no problems at all 
**i had to add the values of the li manually to get over that issue

**Comment by Assone** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.12.7
**Electron Version**: 1.3.13
**System**: Mac OS X 10.12.2
**Thrown From**: [emmet](https://github.com/emmetio/emmet-atom) package, v2.4.3


### Stack Trace

Uncaught Error: Invalid abbreviation

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:871

Error: Invalid abbreviation
    at Object.setAbbreviation (/Users/ali/.atom/packages/emmet-atom-master/node_modules/emmet/lib/parser/abbreviation.js:344:11)
    at parseAbbreviation (/Users/ali/.atom/packages/emmet-atom-master/node_modules/emmet/lib/parser/abbreviation.js:560:14)
    at Object.parse (/Users/ali/.atom/packages/emmet-atom-master/node_modules/emmet/lib/parser/abbreviation.js:890:15)
    at Object.expand (/Users/ali/.atom/packages/emmet-atom-master/node_modules/emmet/lib/parser/abbreviation.js:957:26)
    at Object.handlers.add.order [as fn] (/Users/ali/.atom/packages/emmet-atom-master/node_modules/emmet/lib/action/expandAbbreviation.js:65:25)
    at /Users/ali/.atom/packages/emmet-atom-master/node_modules/emmet/lib/assets/handlerList.js:93:19
    at /Users/ali/.atom/packages/emmet-atom-master/node_modules/emmet/lib/utils/common.js:600:10
    at Array.some (native)
    at Object.find (/Users/ali/.atom/packages/emmet-atom-master/node_modules/emmet/lib/utils/common.js:599:9)
    at Object.exec (/Users/ali/.atom/packages/emmet-atom-master/node_modules/emmet/lib/assets/handlerList.js:92:10)
    at Object.expandAbbreviationAction (/Users/ali/.atom/packages/emmet-atom-master/node_modules/emmet/lib/action/expandAbbreviation.js:110:20)
    at Object.expandAbbreviationWithTabAction (/Users/ali/.atom/packages/emmet-atom-master/node_modules/emmet/lib/action/expandAbbreviation.js:140:14)
    at Object.run (/Users/ali/.atom/packages/emmet-atom-master/node_modules/emmet/lib/action/main.js:150:21)
    at Object.run (/Users/ali/.atom/packages/emmet-atom-master/node_modules/emmet/lib/emmet.js:81:23)
    at runAction (/Users/ali/.atom/packages/emmet-atom-master/lib/emmet.coffee:94:9)
    at /Users/ali/.atom/packages/emmet-atom-master/lib/emmet.coffee:62:9
    at Object.exec (/Users/ali/.atom/packages/emmet-atom-master/lib/editor-proxy.coffee:80:10)
    at /Users/ali/.atom/packages/emmet-atom-master/lib/emmet.coffee:61:19
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:866:18)
    at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1524:26)
    at atom-text-editor.<anonymous> (/Users/ali/.atom/packages/emmet-atom-master/lib/emmet.coffee:60:24)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:259:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:587:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:382:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:106:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -1:04.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  3x -1:02.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:00.6.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -1:00.5.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:58.2.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:56.9.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:55.6.0 autoclose-html:close-and-complete (atom-text-editor.editor.is-focused)
  2x -0:52.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:47.6.0 emmet:expand-abbreviation-with-tab (atom-text-editor.editor.is-focused)
     -0:43.7.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:43.7.0 editor:newline (atom-text-editor.editor.is-focused)
  3x -0:35.4.0 autoclose-html:close-and-complete (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:23.1.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:23.1.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -0:18.4.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:16.9.0 emmet:expand-abbreviation-with-tab (atom-text-editor.editor.is-focused.autocomplete-active)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "simplified-chinese-menu",
      "simplified-chinese-menu",
      "atom-beautify",
      "atom-beautify",
      "linter-ui-default"
    ],
    "telemetryConsent": "limited"
  }
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v1.1.0 (active)
atom-beautify, v0.29.14 (inactive)
atom-html-preview, v0.1.22 (active)
pigments, v0.37.0 (active)
simplified-chinese-menu, v3.5.0 (active)
autoclose-html, v0.23.0 (active)
autocomplete-paths, v1.0.5 (active)
emmet, v2.4.3 (active)
file-icons, v1.7.25 (active)
linter, v1.11.4 (active)
linter, v1.11.4 (active)
linter-ui-default, v0.0.3 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (active)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (active)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (active)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by SyNeto** [comment]
Same error for:
ul>li*5{$}

**Comment by sandro-git** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.13.1
**Electron Version**: 1.3.13
**System**: Mac OS X 10.12.3
**Thrown From**: [w3c-validation](https://github.com/leny/atom-w3c-validation) package, v0.4.0


### Stack Trace

Uncaught Error: Handler must be a function

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:80

Error: Handler must be a function
    at Emitter.module.exports.Emitter.on (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:80:15)
    at TextBuffer.module.exports.TextBuffer.onDidChange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:267:27)
    at /Users/sandro/.atom/packages/w3c-validation/lib/main.js:85:37
    at Workspace.module.exports.Workspace.observeTextEditors (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:329:9)
    at /Users/sandro/.atom/packages/w3c-validation/lib/main.js:83:24
    at /Applications/Atom.app/Contents/Resources/app.asar/src/config.js:618:16
    at /Applications/Atom.app/Contents/Resources/app.asar/src/config.js:635:20
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Config.module.exports.Config.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:826:29)
    at Config.module.exports.Config.setRawValue (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:612:19)
    at Config.module.exports.Config.set (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:227:14)
    at SettingsPanel.module.exports.SettingsPanel.set (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/settings-panel.js:200:28)
    at setNewValue (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/settings-panel.js:136:28)
    at HTMLInputElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/settings-panel.js:142:22)
    at HTMLInputElement.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLInputElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -2:19.3.0 autocomplete-plus:cancel (input.hidden-input)
     -2:18 editor:move-to-end-of-screen-line (input.hidden-input)
  3x -2:15.9.0 core:move-down (input.hidden-input)
     -2:14.6.0 core:save (input.hidden-input)
     -1:47.1.0 command-palette:toggle (input.hidden-input)
     -1:41.1.0 core:close (input.hidden-input)
     -1:34.2.0 core:confirm (input.hidden-input)
  4x -1:22.3.0 core:close (div.panels-item)
  2x -1:13.9.0 tree-view:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:56.1.0 command-palette:toggle (input.hidden-input)
  5x -0:49.2.0 core:backspace (input.hidden-input)
     -0:47.4.0 application:open (input.hidden-input)
     -0:46.4.0 editor:consolidate-selections (input.hidden-input)
     -0:46.4.0 core:cancel (input.hidden-input)
  2x -0:44.1.0 application:open (input.hidden-input)
     -0:31 core:close (input.hidden-input)
```

### Config

```json
{
  "core": {
    "openEmptyEditorOnStart": false,
    "reopenProjectMenuCount": 5,
    "telemetryConsent": "limited",
    "useCustomTitleBar": true
  },
  "w3c-validation": {
    "hideOnNoErrors": true,
    "useFoldModeAsDefault": true,
    "validateOnChange": true
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-paths, v1.0.5 (active)
emmet, v2.4.3 (active)
jquery-snippets, v11.0.0 (active)
linter, v1.11.21 (active)
linter-jshint, v3.0.2 (active)
pigments, v0.39.0 (active)
w3c-validation, v0.4.0 (active)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (active)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (active)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.14.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.33.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.29.0 (inactive)
autosave, v0.23.2 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.43.2 (active)
bracket-matcher, v0.85.1 (active)
command-palette, v0.39.1 (active)
deprecation-cop, v0.55.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.204.5 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.2.0 (active)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.1 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.159.3 (active)
metrics, v1.1.3 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.5 (active)
status-bar, v1.6.0 (active)
styleguide, v0.48.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (active)
timecop, v0.33.2 (active)
tree-view, v0.211.1 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.39.0 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.1 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by jochri3** [comment]
> @cristian-sima `thead>tr>td{0}*6`

Thank man
