### ISSUE TITLE
Uncaught Error: This TextEditor has been destroyed

### ISSUE THREAD

**Issue by Cipa** [emmetio/emmet-atom#276]
[Enter steps to reproduce below:]

1. wrap something(ctrl w)
2. close window
3. try to get rid of the wrap bar by pressing ESC (I get the error)
4. open other file and try to get rid of wrap bar by pressing ESC  (I get the error)

**Atom Version**: 0.200.0
**System**: Mac OS X 10.10.3
**Thrown From**: [emmet](https://github.com/emmetio/emmet-atom) package, v2.3.10

### Stack Trace

Uncaught Error: This TextEditor has been destroyed

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1023

Error: This TextEditor has been destroyed
  at DisplayBuffer.module.exports.DisplayBuffer.screenPositionForBufferPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1023:15)
  at Marker.module.exports.Marker.getHeadScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/marker.js:174:33)
  at Cursor.module.exports.Cursor.getScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:127:26)
  at Cursor.module.exports.Cursor.getScreenRange (/Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:695:20)
  at Cursor.module.exports.Cursor.autoscroll (/Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:700:51)
  at Selection.module.exports.Selection.autoscroll (/Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:897:28)
  at TextEditor.module.exports.TextEditor.undo (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1123:38)
  at PromptView.module.exports.PromptView.undo (/Users/ciMac/.atom/packages/emmet/lib/prompt.coffee:38:11)
  at PromptView.module.exports.PromptView.cancel (/Users/ciMac/.atom/packages/emmet/lib/prompt.coffee:53:4)
  at atom-text-editor.<anonymous> (/Users/ciMac/.atom/packages/emmet/lib/prompt.coffee:23:61)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:519:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:354:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:178:20)

```

### Commands

```
     -2:19.5.0 core:close (atom-text-editor.editor.is-focused)
     -2:08.8.0 core:move-right (atom-text-editor.editor.mini.is-focused)
     -2:02.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:56.2.0 tree-view:move (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -1:55.5.0 editor:move-to-first-character-of-line (atom-text-editor.editor.mini.is-focused)
     -1:54.5.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.mini.is-focused)
 12x -1:53.3.0 editor:move-to-beginning-of-word (atom-text-editor.editor.mini.is-focused)
     -1:51.1.0 editor:move-to-end-of-word (atom-text-editor.editor.mini.is-focused)
     -1:50.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:41.5.0 find-and-replace:show (atom-text-editor.editor.is-focused)
  3x -1:40.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:19.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:06.3.0 core:undo (atom-text-editor.editor.is-focused)
     -1:04.9.0 core:save (atom-text-editor.editor.is-focused)
     -0:01.3.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:01.3.0 core:cancel (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "close-tags",
      "key-peek",
      "less-autocompile",
      "preview",
      "red-wavy-underline",
      "todo-show",
      "linter-phpcs",
      "autoprefixer"
    ],
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "emmet": {}
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
SFTP-deployment, v1.0.0
Sublime-Style-Column-Selection, v1.2.3
atom-beautify, v0.27.4
atom-html-preview, v0.1.6
autoclose-html, v0.16.0
emmet, v2.3.10
highlight-selected, v0.9.3
html-entities, v0.4.0
linter, v0.12.6
linter-csslint, v0.0.13
linter-less, v0.4.0
linter-php, v0.0.15
tabs-to-spaces, v0.10.0
white-cursor, v0.6.0

# Dev
No dev packages
```

**Comment by joseluisq** [comment]
:+1:

**Comment by fourfour** [comment]
+1

**Comment by NKjoep** [comment]
:+1:

**Comment by NerdPad** [comment]
+1

**Comment by dannymichel** [comment]
Haha, this is the funniest error i've ever seen.

**Comment by joseluisq** [comment]
@dannymichel Sure ! 
This sounds like if my text editor was killed by John Connor Haha

**Comment by tobyl** [comment]
+1

**Comment by adam-dorin** [comment]
+1

**Comment by AaronLeoCooper** [comment]
+1

**Comment by boxmein** [comment]
Still getting it.
