### ISSUE TITLE
Cannot Find Module 'Emmet'

### ISSUE THREAD

**Issue by badgerfan3** [emmetio/emmet-atom#277]
[Enter steps to reproduce below:]

1. ... Install Package
2. ... Run Atom

**Atom Version**: 0.201.0
**System**: Microsoft Windows 8.1
**Thrown From**: [emmet-atom](https://github.com/emmetio/emmet-atom) package, v2.3.10

### Stack Trace

Failed to load the emmet-atom package

```
At Cannot find module 'emmet'

Error: Cannot find module 'emmet'
    at Module._resolveFilename (module.js:328:15)
    at Function.Module._resolveFilename (C:\Users\Caleb\AppData\Local\atom\app-0.201.0\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (C:\Users\Caleb\.atom\packages\emmet-atom\lib\emmet.coffee:10:11)
    at Object.<anonymous> (C:\Users\Caleb\.atom\packages\emmet-atom\lib\emmet.coffee:200:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (C:\Users\Caleb\AppData\Local\atom\app-0.201.0\resources\app.asar\node_modules\coffee-cash\lib\coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-syntax"
    ],
    "disabledPackages": [
      "atom-auto-update-packages"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-achievements, v0.7.2
atom-jshint, v2.0.0
atom-spotify, v1.2.0
color-picker, v1.7.0
emmet-atom, v2.3.10
seti-syntax, v0.4.0
seti-ui, v0.7.1

# Dev
No dev packages
```

**Comment by mitchellbutler** [comment]
Make sure you've installed the required node modules in the "Install Package" step. Try `cd ~/.atom/packages/emmet-atom/` followed by `npm install` and read the output to confirm the required modules install correctly. If you install the package without following this step it will produce this message.
