### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by Reegan01** [emmetio/emmet-atom#280]
**Atom Version**: 0.207.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [emmet-atom](https://github.com/emmetio/emmet-atom) package, v2.3.2

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At C:\Users\reegan\AppData\Local\atom\app-0.207.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:741

TypeError: undefined is not a function
  at runAction (C:\Users\reegan\.atom\packages\emmet-atom\lib\emmet.coffee:57:25)
  at C:\Users\reegan\.atom\packages\emmet-atom\lib\emmet.coffee:46:9
  at Object.module.exports.exec (C:\Users\reegan\.atom\packages\emmet-atom\lib\editor-proxy.coffee:77:10)
  at C:\Users\reegan\.atom\packages\emmet-atom\lib\emmet.coffee:45:19
  at TextBuffer.module.exports.TextBuffer.transact (C:\Users\reegan\AppData\Local\atom\app-0.207.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:736:18)
  at TextEditor.module.exports.TextEditor.transact (C:\Users\reegan\AppData\Local\atom\app-0.207.0\resources\app.asar\src\text-editor.js:1147:26)
  at atom-text-editor.<anonymous> (C:\Users\reegan\.atom\packages\emmet-atom\lib\emmet.coffee:44:24)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\reegan\AppData\Local\atom\app-0.207.0\resources\app.asar\src\command-registry.js:238:29)
  at C:\Users\reegan\AppData\Local\atom\app-0.207.0\resources\app.asar\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\reegan\AppData\Local\atom\app-0.207.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\reegan\AppData\Local\atom\app-0.207.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\reegan\AppData\Local\atom\app-0.207.0\resources\app.asar\src\window-event-handler.js:177:20)

```

### Commands

```
     -1:16.2.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -1:15.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:08.3.0 core:paste (atom-text-editor.editor.is-focused)
  6x -0:06.8.0 core:select-up (atom-text-editor.editor.is-focused)
     -0:04.9.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -0:04.6.0 emmet:expand-abbreviation-with-tab (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "bluebliss-2"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autoclose-html, v0.17.1
bluebliss-2, v0.7.0
bookmarklet, v0.7.1
color-picker, v2.0.4
emmet, v2.3.10
emmet-atom, v2.3.2
javascript-snippets, v1.0.0
linter-tidy, v1.0.1
seti-ui, v0.7.1

# Dev
No dev packages
```

**Comment by sergeche** [comment]
There’s should be only one `emmet` plugin, but you have `emmet` and `emmet-atom`. Please remove the last one

**Comment by Reegan01** [comment]
It's working Thanks for your reply ..God Bless
