### ISSUE TITLE
Failed to load the emmet package

### ISSUE THREAD

**Issue by neticcul2se** [emmetio/emmet-atom#286]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.3
**Thrown From**: [emmet](https://github.com/emmetio/emmet-atom) package, v2.3.10

### Stack Trace

Failed to load the emmet package

```
At Cannot find module 'emmet'

Error: Cannot find module 'emmet'
  at Module._resolveFilename (module.js:328:15)
  at Function.Module._resolveFilename (/Users/Apple/Desktop/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:270:25)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/Apple/.atom/packages/emmet-atom/lib/emmet.coffee:5:9)
  at Object.<anonymous> (/Users/Apple/.atom/packages/emmet-atom/lib/emmet.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Users/Apple/Desktop/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (/Users/Apple/Desktop/Atom.app/Contents/Resources/app.asar/src/package.js:709:34)
  at /Users/Apple/Desktop/Atom.app/Contents/Resources/app.asar/src/package.js:188:28
  at Package.module.exports.Package.measure (/Users/Apple/Desktop/Atom.app/Contents/Resources/app.asar/src/package.js:165:15)
  at Package.module.exports.Package.load (/Users/Apple/Desktop/Atom.app/Contents/Resources/app.asar/src/package.js:179:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/Users/Apple/Desktop/Atom.app/Contents/Resources/app.asar/src/package-manager.js:372:14)
  at PackageManager.module.exports.PackageManager.loadPackages (/Users/Apple/Desktop/Atom.app/Contents/Resources/app.asar/src/package-manager.js:336:14)
  at Atom.module.exports.Atom.startEditorWindow (/Users/Apple/Desktop/Atom.app/Contents/Resources/app.asar/src/atom.js:638:21)
  at Object.<anonymous> (/Users/Apple/Desktop/Atom.app/Contents/Resources/app.asar/src/window-bootstrap.js:12:8)
  at Object.<anonymous> (/Users/Apple/Desktop/Atom.app/Contents/Resources/app.asar/src/window-bootstrap.js:23:4)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/Users/Apple/Desktop/Atom.app/Contents/Resources/app.asar/src/babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at setupWindow (file:///Users/Apple/Desktop/Atom.app/Contents/Resources/app.asar/static/index.js:96:23)
  at window.onload (file:///Users/Apple/Desktop/Atom.app/Contents/Resources/app.asar/static/index.js:36:7)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-html-preview, v0.1.8

# Dev
No dev packages
```

**Comment by sergeche** [comment]
It looks like you didn’t installed Emmet properly. Try to re-install it

**Comment by MazheM** [comment]
I have the same problem now. Re-install doesnt help.

**Comment by Sej7** [comment]
Hi! I have the same problem. I have started to learn coding. Our teacher uses Atom. I don't know what to do. Help me please.


[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Unknown Windows Version
**Thrown From**: [emmet](https://github.com/emmetio/emmet-atom) package, v2.3.13


### Stack Trace

Failed to load the emmet package

```
At Cannot find module 'emmet'

Error: Cannot find module 'emmet'
    at Module._resolveFilename (module.js:334:15)
    at Function.Module._resolveFilename (C:\Users\Алина\AppData\Local\atom\app-1.0.19\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:284:25)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (C:\Users\Алина\.atom\packages\emmet\lib\emmet.coffee:5:9)
    at Object.<anonymous> (C:\Users\Алина\.atom\packages\emmet\lib\emmet.coffee:1:1)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .coffee] (C:\Users\Алина\AppData\Local\atom\app-1.0.19\resources\app.asar\src\compile-cache.js:169:21)
    at Module.load (module.js:353:32)
```

### Commands

```
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
emmet, v2.3.13

# Dev
No dev packages
```

**Comment by sergeche** [comment]
It means Emmet is not properly installed, e.g. there’s no core `emmet` package that should be installed by NPM.

Try the following:

1. In command prompt/console go to Emmet package folder (in your case it’s `C:\Users\Алина\.atom\packages\emmet`)
2. Run `npm install`. You may need to install Node.js/NPM before doing so.
3. Restart Atom

**Comment by Sej7** [comment]
Thank you. I did all that ou told but without changes. Result is below.
![2015-10-01_213536](https://cloud.githubusercontent.com/assets/12980365/10230286/f5b447ee-6884-11e5-9f62-8caeb7bb4142.jpg)

**Comment by sergeche** [comment]
Do you have `C:\Users\Алина\.atom\packages\emmet\node_modules\emmet` folder with some JS files in it?

**Comment by Sej7** [comment]
Yes, I have. There are many files with extention ".js"

**Comment by YunSeongha** [comment]
I had the same problem. recommend Re-install 'atom'

**Comment by MazheM** [comment]
I tried a complete reinstall of the atom, but it did not help, getting this error when installing.

**Comment by MazheM** [comment]
It seems this is Atom problem:
https://github.com/atom/atom/issues/8891
https://discuss.atom.io/t/atom-throwing-several-failed-to-load-the-xyz-package-errors/20969

Possible problem: user profile folder contains non-latin characters in name.
Possible solution: change user profile folder name.(I tried this but after changing some rights on the folder, Windows has ceased to work correctly with the profile folder and I reinstalled Windows completely. Now Atom and Emmet are working properly.). Or create a new profile, where there is no non-Latin characters in the name.

**Comment by sergeche** [comment]
Thanks for the heads-up, @MazheM :+1:

**Comment by raylhx** [comment]
cd .atom/packages
$ git clone https://github.com/emmetio/emmet-atom         (windows)
$ cd emmet-atom
$ npm install
and ok~

**Comment by Fallen-Angle-Lucifer** [comment]
This problem is because you don't have node.js and npm.
You can install node.js and npm,then try it again.

**Comment by lordbrad123** [comment]
I am using a translator.
I got the same error and what I did was to install the atom-nodejs-snipptes then uninstall the emmet delete in the package the emmet I installed by console and then I could install the emmet quietly

**Comment by ochedenis** [comment]
fix this by typing: "npm install" on console (~ / .atom / packages / emmet-atom (from this directory))
at installing was mistake, and console recommended to use another command

**Comment by happyboredom** [comment]
Clearing the compile cache resolved the issue for me on Mac.

https://discuss.atom.io/t/atom-throwing-several-failed-to-load-the-xyz-package-errors/20969/3

```
Try this:

Completely close all instances of Atom
Delete the directory ~/.atom/compile-cache
Start Atom again
```
