### ISSUE TITLE
Uncaught Error: Cannot find module 'atom-space-pen-views'

### ISSUE THREAD

**Issue by sayful1** [emmetio/emmet-atom#302]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Ubuntu 14.10
**Thrown From**: [emmet](https://github.com/emmetio/emmet-atom) package, v2.3.12

### Stack Trace

Uncaught Error: Cannot find module 'atom-space-pen-views'

```
At module.js:330

Error: Cannot find module 'atom-space-pen-views'
  at Module._resolveFilename (module.js:328:15)
  at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:270:25)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/home/sayful/.atom/packages/emmet-atom/lib/prompt.coffee:1:29)
  at Object.<anonymous> (/home/sayful/.atom/packages/emmet-atom/lib/prompt.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/usr/share/atom/resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/home/sayful/.atom/packages/emmet-atom/lib/interactive.js:16:18)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/usr/share/atom/resources/app.asar/src/babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at atom-text-editor._results.push.actions.(anonymous function) (/home/sayful/.atom/packages/emmet-atom/lib/emmet.coffee:102:23)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:241:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:180:20)

```

### Commands

```
  4x -0:18.5.0 emmet:expand-abbreviation-with-tab (atom-text-editor.editor.is-focused)
     -0:09.5.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:04.2.0 editor:newline-above (atom-text-editor.editor.is-focused)
     -0:02.7.0 core:undo (atom-text-editor.editor.is-focused)
     -0:01.0 emmet:interactive-expand-abbreviation (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by sergeche** [comment]
You Emmet package was installed incorrectly. Try to re-install it
