### ISSUE TITLE
Uncaught Error: Invalid attribute set

### ISSUE THREAD

**Issue by SpikeShape** [emmetio/emmet-atom#305]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.2
**System**: SYSTEM
**Thrown From**: [emmet](https://github.com/emmetio/emmet-atom) package, v2.3.12

### Stack Trace

Uncaught Error: Invalid attribute set

```
At C:\Users\ruediger\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:745

Error: Invalid attribute set
    at splitAttributes (C:\Users\ruediger\.atom\packages\emmet\node_modules\emmet\lib\parser\abbreviation.js:595:12)
    at extractAttributes (C:\Users\ruediger\.atom\packages\emmet\node_modules\emmet\lib\parser\abbreviation.js:630:10)
    at parseAttributes (C:\Users\ruediger\.atom\packages\emmet\node_modules\emmet\lib\parser\abbreviation.js:712:7)
    at Object.AbbreviationNode.setAbbreviation (C:\Users\ruediger\.atom\packages\emmet\node_modules\emmet\lib\parser\abbreviation.js:334:20)
    at parseAbbreviation (C:\Users\ruediger\.atom\packages\emmet\node_modules\emmet\lib\parser\abbreviation.js:560:14)
    at Object.parse (C:\Users\ruediger\.atom\packages\emmet\node_modules\emmet\lib\parser\abbreviation.js:890:15)
    at Object.expand (C:\Users\ruediger\.atom\packages\emmet\node_modules\emmet\lib\parser\abbreviation.js:957:26)
    at Object.handlers.add.order [as fn] (C:\Users\ruediger\.atom\packages\emmet\node_modules\emmet\lib\action\expandAbbreviation.js:65:25)
    at C:\Users\ruediger\.atom\packages\emmet\node_modules\emmet\lib\assets\handlerList.js:93:19
    at C:\Users\ruediger\.atom\packages\emmet\node_modules\emmet\lib\utils\common.js:600:10
    at Array.some (native)
    at Object.find (C:\Users\ruediger\.atom\packages\emmet\node_modules\emmet\lib\utils\common.js:599:9)
    at Object.HandlerList.exec (C:\Users\ruediger\.atom\packages\emmet\node_modules\emmet\lib\assets\handlerList.js:92:10)
    at Object.expandAbbreviationAction (C:\Users\ruediger\.atom\packages\emmet\node_modules\emmet\lib\action\expandAbbreviation.js:110:20)
    at Object.expandAbbreviationWithTabAction (C:\Users\ruediger\.atom\packages\emmet\node_modules\emmet\lib\action\expandAbbreviation.js:140:14)
    at Object.run (C:\Users\ruediger\.atom\packages\emmet\node_modules\emmet\lib\action\main.js:150:21)
```

### Commands

```
     -0:22.9.0 core:undo (atom-text-editor.editor.is-focused)
     -0:21.2.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:20.9.0 core:move-down (atom-text-editor.editor.is-focused)
  2x -0:20.6.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:20.2.0 editor:select-to-end-of-word (atom-text-editor.editor.is-focused)
     -0:18.9.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:18.9.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:18.7.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:18.5.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -0:18.3.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:18.3.0 editor:newline (atom-text-editor.editor.is-focused)
  3x -0:11.1.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:07.3.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:05.6.0 core:select-left (atom-text-editor.editor.is-focused)
     -0:03.5.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -0:03.4.0 emmet:expand-abbreviation-with-tab (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "terminal-status",
      "achievements",
      "save-session"
    ],
    "ignoredNames": [
      "node_modules",
      "components/libs/"
    ],
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-paths, v1.0.2
color-picker, v2.0.10
editorconfig, v1.0.1
emmet, v2.3.12
linter, v1.2.3
minimap, v4.11.2
minimap-bookmarks, v0.1.0
minimap-find-and-replace, v4.2.0
minimap-git-diff, v4.1.6
minimap-highlight-selected, v4.3.0
minimap-pigments, v0.1.1
minimap-selection, v4.3.0
pigments, v0.8.4
project-manager, v1.15.11
seti-syntax, v0.4.0
seti-ui, v0.7.1
terminal-panel, v1.14.1

# Dev
No dev packages
```

**Comment by SpikeShape** [comment]
Updated steps to re-produce the error
