### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by hannesjohansson** [emmetio/emmet-atom#32]
Hi,

I'm having problems installing this package:

```
npm http GET https://registry.npmjs.org/season
npm http GET https://registry.npmjs.org/season
npm http GET https://registry.npmjs.org/season
npm http GET https://registry.npmjs.org/season/-/season-1.0.2.tgz
npm ERR! fetch failed https://registry.npmjs.org/season/-/season-1.0.2.tgz
npm http GET https://registry.npmjs.org/season/-/season-1.0.2.tgz
npm ERR! fetch failed https://registry.npmjs.org/season/-/season-1.0.2.tgz
npm http GET https://registry.npmjs.org/season/-/season-1.0.2.tgz
npm ERR! fetch failed https://registry.npmjs.org/season/-/season-1.0.2.tgz
npm ERR! Error: SELF_SIGNED_CERT_IN_CHAIN
npm ERR!     at TLSSocket.<anonymous> (_tls_wrap.js:777:36)
npm ERR!     at TLSSocket.EventEmitter.emit (events.js:98:17)
npm ERR!     at TLSSocket._finishInit (_tls_wrap.js:337:8)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/isaacs/npm/issues>

npm ERR! System Darwin 13.0.2
npm ERR! command "/Applications/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/Atom Helper" "/Applications/Atom.app/Contents/Resources/app/node_modules/atom-package-manager/node_modules/npm/bin/npm-cli.js" "--userconfig" "/Applications/Atom.app/Contents/Resources/app/node_modules/atom-package-manager/.apmrc" "install" "/Users/hannes.johansson/.atom/.node-gyp/.atom/.apm/emmet/0.4.1/package.tgz" "--target=0.11.10" "--arch=x64"
npm ERR! cwd /private/var/folders/3l/8s9sfz7x1mlbwtvcdrz1sqt4fd3575/T/apm-install-dir-114128-5355-1n8eo3s
npm ERR! node -v v0.11.10
npm ERR! npm -v 1.3.18
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /private/var/folders/3l/8s9sfz7x1mlbwtvcdrz1sqt4fd3575/T/apm-install-dir-114128-5355-1n8eo3s/npm-debug.log
npm ERR! not ok code 0
```

**Comment by AbdelbassitGuellati** [comment]
i'm not able to install Emmet packaege on Atom, however [i'm](url) getting this error msg!
could someone help me please to install it??

nstalling “emmet@2.4.3” failed.Hide output…

npm ERR! Unexpected end of JSON input while parsing near '...cjiy27dkG\nOfRoApz7iu'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\sise\.atom\.apm\_logs\2021-06-23T18_52_09_823Z-debug.log

![Capture d’écran 2021-06-23 195621](https://user-images.githubusercontent.com/86374037/123153118-3ddef100-d45d-11eb-8456-b000de4a2224.png)

**Comment by sergeche** [comment]
It's not Emmet issue, it's either Atom or your network provider issue

**Comment by AbdelbassitGuellati** [comment]
> It's not Emmet issue, it's either Atom or your network provider issue

i see, could you help me to fix it please
