### ISSUE TITLE
Failed to activate the minimap package

### ISSUE THREAD

**Issue by denismeister** [emmetio/emmet-atom#339]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Unknown Windows Version
**Thrown From**: [emmet](https://github.com/emmetio/emmet-atom) package, v2.3.13

### Stack Trace

Failed to activate the minimap package

```
At Cannot find module 'atom-utils'

Error: Cannot find module 'atom-utils'
  at Module._resolveFilename (module.js:334:15)
  at Function.Module._resolveFilename (D:\GoogleDrive\Web programs portable\Atom\resources\app.asar\src\module-cache.js:383:52)
  at Function.Module._load (module.js:284:25)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (C:\Users\Денис\.atom\packages\minimap\lib\minimap-element.coffee:3:40)
  at Object.<anonymous> (C:\Users\Денис\.atom\packages\minimap\lib\minimap-element.coffee:1:1)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .coffee] (D:\GoogleDrive\Web programs portable\Atom\resources\app.asar\src\compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Main.activate (C:\Users\Денис\.atom\packages\minimap\lib\main.coffee:102:23)
  at Package.module.exports.Package.activateNow (D:\GoogleDrive\Web programs portable\Atom\resources\app.asar\src\package.js:245:19)
  at D:\GoogleDrive\Web programs portable\Atom\resources\app.asar\src\package.js:226:30
  at Package.module.exports.Package.measure (D:\GoogleDrive\Web programs portable\Atom\resources\app.asar\src\package.js:169:15)
  at Package.module.exports.Package.activate (D:\GoogleDrive\Web programs portable\Atom\resources\app.asar\src\package.js:218:14)
  at PackageManager.module.exports.PackageManager.activatePackage (D:\GoogleDrive\Web programs portable\Atom\resources\app.asar\src\package-manager.js:486:21)
  at D:\GoogleDrive\Web programs portable\Atom\resources\app.asar\node_modules\settings-view\lib\package-manager.js:371:29
  at exit (D:\GoogleDrive\Web programs portable\Atom\resources\app.asar\node_modules\settings-view\lib\package-manager.js:60:16)
  at triggerExitCallback (D:\GoogleDrive\Web programs portable\Atom\resources\app.asar\src\buffered-process.js:213:47)
  at ChildProcess.<anonymous> (D:\GoogleDrive\Web programs portable\Atom\resources\app.asar\src\buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:172:7)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

```

### Commands

```
  2x -4:54.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
emmet, v2.3.13
minimap, v4.13.4

# Dev
No dev packages
```

**Comment by sergeche** [comment]
https://github.com/emmetio/emmet-atom/issues/286#issuecomment-148200443

**Comment by jason588** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Unknown Windows Version
**Thrown From**: [emmet](https://github.com/emmetio/emmet-atom) package, v2.3.13


### Stack Trace

Failed to load the emmet package

```
At Cannot find module 'emmet'

Error: Cannot find module 'emmet'
  at Module._resolveFilename (module.js:334:15)
  at Function.Module._resolveFilename (C:\Users\宏亮\AppData\Local\atom\app-1.1.0\resources\app.asar\src\module-cache.js:383:52)
  at Function.Module._load (module.js:284:25)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (C:\Users\宏亮\.atom\packages\emmet\lib\emmet.coffee:5:9)
  at Object.<anonymous> (C:\Users\宏亮\.atom\packages\emmet\lib\emmet.coffee:1:1)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .coffee] (C:\Users\宏亮\AppData\Local\atom\app-1.1.0\resources\app.asar\src\compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Package.module.exports.Package.requireMainModule (C:\Users\宏亮\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package.js:725:34)
  at C:\Users\宏亮\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package.js:176:28
  at Package.module.exports.Package.measure (C:\Users\宏亮\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package.js:153:15)
  at Package.module.exports.Package.load (C:\Users\宏亮\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package.js:167:12)
  at PackageManager.module.exports.PackageManager.loadPackage (C:\Users\宏亮\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package-manager.js:396:14)
  at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\宏亮\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package-manager.js:473:30)
  at C:\Users\宏亮\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:444:29
  at exit (C:\Users\宏亮\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:73:16)
  at triggerExitCallback (C:\Users\宏亮\AppData\Local\atom\app-1.1.0\resources\app.asar\src\buffered-process.js:213:47)
  at ChildProcess.<anonymous> (C:\Users\宏亮\AppData\Local\atom\app-1.1.0\resources\app.asar\src\buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:172:7)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

```

### Commands

```
     -5:34.1.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
  7x -5:31.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -5:27.6.0 core:move-down (atom-text-editor.editor.is-focused.autocomplete-active)
     -5:27 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
  6x -5:24.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -5:12.2.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -5:12.2.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
     -4:34.5.0 core:copy (atom-text-editor.editor.is-focused)
     -4:05.2.0 core:save (atom-text-editor.editor.is-focused)
  2x -3:59.4.0 symbols-view:toggle-file-symbols (atom-text-editor.editor.is-focused)
     -3:22.2.0 application:new-file (atom-text-editor.editor.is-focused)
     -3:15.9.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -3:15.9.0 snippets:expand (atom-text-editor.editor.is-focused)
     -3:15.9.0 editor:indent (atom-text-editor.editor.is-focused)
     -3:14.6.0 core:undo (atom-text-editor.editor.is-focused)
     -3:13.5.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
color-picker, v2.0.13
emmet, v2.3.13

# Dev
No dev packages
```
