### ISSUE TITLE
Uncaught Error : ENONET

### ISSUE THREAD

**Issue by Shaq7** [emmetio/emmet-atom#356]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.3
**System**: Mac OS X 10.11.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/Users/shaq/Desktop/Softwares/Atom.app'

```
At ATOM_SHELL_ASAR.js:0

Error: ENOENT: no such file or directory, lstat '/Users/shaq/Desktop/Softwares/Atom.app'
    at Error (native)
    at fs.lstatSync (fs.js:844:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:189:16)
    at realpathSync (fs.js:1454:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:272:24)
    at toRealPath (module.js:109:13)
    at Function.Module._findPath (module.js:149:20)
    at Module._resolveFilename (module.js:334:25)
    at Function.Module._resolveFilename (/Users/shaq/Desktop/Softwares/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
```

### Commands

```
  2x -8:33.5.0 emmet:wrap-with-abbreviation (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  8x -8:21.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -8:10.6.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -8:10.6.0 editor:newline (atom-text-editor.editor.is-focused)
 11x -8:07.4.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -7:55.7.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -7:55.7.0 core:cancel (atom-text-editor.editor.mini.is-focused)
  5x -7:54.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -7:52.5.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -7:52.5.0 editor:newline (atom-text-editor.editor.is-focused)
     -7:50.7.0 emmet:wrap-with-abbreviation (atom-text-editor.editor.is-focused)
     -7:44.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -7:41.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -7:33.8.0 core:backspace (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {},
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by cybersam** [comment]
Can someone with edit access please correct the title of this issue by replacing "ENONET" with "ENOENT"? This will save some time for people (like me) searching online for "ENONET"; this issue is one of the first ones shown by Google.
