### ISSUE TITLE
Expand Abbreviation from PHP echo - Uncaught TypeError: Cannot read property 'value' of null

### ISSUE THREAD

**Issue by voermansm** [emmetio/emmet-atom#362]
1. Expand abbreviation from PHP file
2. echo 'div.test';

This use to work in past releases.

**Atom Version**: 1.2.4
**System**: Mac OS X 10.11.1
**Thrown From**: [emmet](https://github.com/emmetio/emmet-atom) package, v2.3.15

### Stack Trace

Uncaught TypeError: Cannot read property 'value' of null

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:770

TypeError: Cannot read property 'value' of null
    at [object Object].EditElement (/Users/mikevoermans/.atom/packages/emmet/node_modules/emmet/lib/editTree/base.js:320:25)
    at new child (/Users/mikevoermans/.atom/packages/emmet/node_modules/emmet/lib/vendor/klass.js:35:12)
    at [object Object].<anonymous> (/Users/mikevoermans/.atom/packages/emmet/node_modules/emmet/lib/editTree/xml.js:54:27)
    at Array.forEach (native)
    at [object Object].editTree.EditContainer.extend.initialize (/Users/mikevoermans/.atom/packages/emmet/node_modules/emmet/lib/editTree/xml.js:35:11)
    at [object Object].EditContainer (/Users/mikevoermans/.atom/packages/emmet/node_modules/emmet/lib/editTree/base.js:66:19)
    at new child (/Users/mikevoermans/.atom/packages/emmet/node_modules/emmet/lib/vendor/klass.js:35:12)
    at Object.parse (/Users/mikevoermans/.atom/packages/emmet/node_modules/emmet/lib/editTree/xml.js:227:11)
    at Object.captureContext (/Users/mikevoermans/.atom/packages/emmet/node_modules/emmet/lib/utils/action.js:181:32)
    at Object.handlers.add.order [as fn] (/Users/mikevoermans/.atom/packages/emmet/node_modules/emmet/lib/action/expandAbbreviation.js:68:30)
    at /Users/mikevoermans/.atom/packages/emmet/node_modules/emmet/lib/assets/handlerList.js:93:19
    at /Users/mikevoermans/.atom/packages/emmet/node_modules/emmet/lib/utils/common.js:600:10
    at Array.some (native)
    at Object.find (/Users/mikevoermans/.atom/packages/emmet/node_modules/emmet/lib/utils/common.js:599:9)
    at Object.HandlerList.exec (/Users/mikevoermans/.atom/packages/emmet/node_modules/emmet/lib/assets/handlerList.js:92:10)
    at Object.expandAbbreviationAction (/Users/mikevoermans/.atom/packages/emmet/node_modules/emmet/lib/action/expandAbbreviation.js:110:20)
    at Object.run (/Users/mikevoermans/.atom/packages/emmet/node_modules/emmet/lib/action/main.js:150:21)
    at Object.run (/Users/mikevoermans/.atom/packages/emmet/node_modules/emmet/lib/emmet.js:81:23)
    at runAction (/Users/mikevoermans/.atom/packages/emmet/lib/emmet.coffee:92:12)
    at /Users/mikevoermans/.atom/packages/emmet/lib/emmet.coffee:57:1
    at Object.module.exports.exec (/Users/mikevoermans/.atom/packages/emmet/lib/editor-proxy.coffee:80:10)
    at /Users/mikevoermans/.atom/packages/emmet/lib/emmet.coffee:1:1
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:765:18)
    at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1152:26)
    at atom-text-editor.<anonymous> (/Users/mikevoermans/.atom/packages/emmet/lib/emmet.coffee:47:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:533:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:356:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:99:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:52.2.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:52.2.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:44.2.0 emmet:expand-abbreviation (atom-text-editor.editor.is-focused)
     -0:32.9.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-base16-tomorrow-dark-theme.theme-neutron-ui)
     -0:03.9.0 emmet:expand-abbreviation (atom-text-editor.editor.is-focused)
     -0:02.9.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:02.9.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:00.7.0 emmet:expand-abbreviation (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".sass-cache"
    ],
    "disabledPackages": [
      "minimap",
      "linter-scss-lint",
      "linter-php",
      "linter-jshint",
      "linter-coffeelint",
      "linter"
    ],
    "themes": [
      "neutron-ui",
      "base16-tomorrow-dark-theme"
    ]
  },
  "emmet": {}
}
```

### Installed Packages

```coffee
# User
color-picker, v2.0.13
emmet, v2.3.15
file-icons, v1.6.12
neutron-ui, v0.4.0
project-manager, v2.6.5

# Dev
No dev packages
```

**Comment by MurKit** [comment]
I have this problem when press Enterin php file after not closed single quotes.

**Comment by mateddy** [comment]
Got the same problem as @MurKit did.  Any fix yet?

**Comment by sergeche** [comment]
I’m working on a completely new Emmet implementation, please wait for next release 😎

**Comment by MurKit** [comment]
Wow, good news!

**Comment by kurianbenoy** [comment]
I too get the same problem when I press enter after a <script> tag in bootstrap

**Comment by psantos10** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.20.1 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [emmet](https://github.com/emmetio/emmet-atom) package 2.4.3


### Stack Trace

Uncaught TypeError: Cannot read property 'value' of null

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:899

TypeError: Cannot read property 'value' of null
    at child.EditElement (/packages/emmet/node_modules/emmet/lib/editTree/base.js:320:25)
    at /packages/emmet/node_modules/emmet/lib/vendor/klass.js:35:12)
    at /packages/emmet/node_modules/emmet/lib/editTree/xml.js:54:27)
    at Array.forEach (native)
    at child.initialize (/packages/emmet/node_modules/emmet/lib/editTree/xml.js:35:11)
    at child.EditContainer (/packages/emmet/node_modules/emmet/lib/editTree/base.js:66:19)
    at /packages/emmet/node_modules/emmet/lib/vendor/klass.js:35:12)
    at Object.parse (/packages/emmet/node_modules/emmet/lib/editTree/xml.js:227:11)
    at Object.parseFromPosition (/packages/emmet/node_modules/emmet/lib/editTree/xml.js:242:16)
    at Object.styleAttrRange (/packages/emmet/node_modules/emmet/lib/utils/cssSections.js:521:27)
    at Object.isInlineCSS (/packages/emmet/node_modules/emmet/lib/utils/action.js:336:25)
    at Object.detectSyntax (/packages/emmet/node_modules/emmet/lib/utils/action.js:255:58)
    at Object.getSyntax (/packages/emmet/lib/editor-proxy.coffee:223:17)
    at runAction (/packages/emmet/lib/emmet.coffee:66:24)
    at /packages/emmet/lib/emmet.coffee:62:9
    at Object.exec (/packages/emmet/lib/editor-proxy.coffee:80:10)
    at /packages/emmet/lib/emmet.coffee:61:19
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:894:24)
    at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1673:32)
    at /packages/emmet/lib/emmet.coffee:60:24)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:35)
    at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
  4x -4:24.2.0 core:backspace (input.hidden-input)
  3x -4:22.5.0 core:save (input.hidden-input)
     -4:21.6.0 emmet:insert-formatted-line-break-only (input.hidden-input)
     -4:21.6.0 editor:newline (input.hidden-input)
  2x -4:21.3.0 core:save (input.hidden-input)
  2x -4:04.0 core:backspace (input.hidden-input)
  2x -4:03.3.0 core:save (input.hidden-input)
     -3:57.5.0 core:move-right (input.hidden-input)
  5x -3:57.2.0 core:backspace (input.hidden-input)
  3x -3:56.1.0 core:save (input.hidden-input)
  3x -3:49 core:backspace (input.hidden-input)
     -3:48.1.0 core:save (input.hidden-input)
  3x -0:32.6.0 core:backspace (input.hidden-input)
  2x -0:31.7.0 core:save (input.hidden-input)
  8x -0:28.2.0 core:backspace (input.hidden-input)
  2x -0:26.6.0 emmet:insert-formatted-line-break-only (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.5 
atom-live-server 2.1.2 
atom-typescript 11.0.9 
busy-signal 1.4.3 
emmet 2.4.3 
file-icons 2.1.12 
git-control 0.9.0 
highlight-selected 0.13.1 
intentions 1.1.5 
language-elixir 0.20.3 
language-kotlin 0.5.0 
language-vue 0.23.1 
linter 2.2.0 
linter-erb 1.1.0 
linter-eslint 8.3.2 
linter-php 1.5.1 
linter-rubocop 2.2.0 
linter-ui-default 1.6.10 
minimap 4.29.7 
project-manager 3.3.5 
rails-rspec 0.3.2 
rails-snippets 2.16.0 
todo-show 2.0.0 
```

**Comment by henryle2011** [comment]
Hi, I am new to Programming and Emmet and got this error on Atom. How can I fix this? Cheers!
