### ISSUE TITLE
Uncaught TypeError: Cannot read property 'path' of null

### ISSUE THREAD

**Issue by gad2103** [emmetio/emmet-atom#367]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.4
**System**: Mac OS X 10.11.1
**Thrown From**: [emmet](https://github.com/emmetio/emmet-atom) package, v2.3.16

### Stack Trace

Uncaught TypeError: Cannot read property 'path' of null

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:770

TypeError: Cannot read property 'path' of null
    at Object.module.exports.getFilePath (/Users/gabrielduncan/.atom/packages/emmet/lib/editor-proxy.coffee:237:24)
    at encodeToBase64 (/Users/gabrielduncan/.atom/packages/emmet/node_modules/emmet/lib/action/base64.js:40:27)
    at Object.encodeDecodeDataUrlAction (/Users/gabrielduncan/.atom/packages/emmet/node_modules/emmet/lib/action/base64.js:131:13)
    at Object.run (/Users/gabrielduncan/.atom/packages/emmet/node_modules/emmet/lib/action/main.js:150:21)
    at Object.run (/Users/gabrielduncan/.atom/packages/emmet/node_modules/emmet/lib/emmet.js:81:23)
    at runAction (/Users/gabrielduncan/.atom/packages/emmet/lib/emmet.coffee:92:12)
    at /Users/gabrielduncan/.atom/packages/emmet/lib/emmet.coffee:57:1
    at Object.module.exports.exec (/Users/gabrielduncan/.atom/packages/emmet/lib/editor-proxy.coffee:80:10)
    at /Users/gabrielduncan/.atom/packages/emmet/lib/emmet.coffee:1:1
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:765:18)
    at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1152:26)
    at atom-text-editor.<anonymous> (/Users/gabrielduncan/.atom/packages/emmet/lib/emmet.coffee:47:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:533:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:356:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:99:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -2:21.9.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -2:21.9.0 snippets:expand (atom-text-editor.editor.is-focused)
     -2:21.9.0 editor:indent (atom-text-editor.editor.is-focused)
     -2:07.4.0 editor:select-to-end-of-line (atom-text-editor.editor.is-focused)
     -1:52.4.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -1:37 core:move-left (atom-text-editor.editor.is-focused)
  3x -1:31.9.0 core:undo (atom-text-editor.editor.is-focused)
     -1:08.2.0 core:move-down (atom-text-editor.editor.is-focused)
     -1:06.1.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -1:06.1.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:04.9.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -1:04.9.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:01.1.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:47.9.0 core:copy (atom-text-editor.editor.is-focused)
  2x -0:44.4.0 core:undo (atom-text-editor.editor.is-focused)
     -0:01.1.0 emmet:encode-decode-data-url (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "vim-mode"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Stylus, v1.2.1
angularjs, v0.3.3
atom-jade, v0.3.0
emmet, v2.3.16
linter, v1.11.3
linter-eslint, v5.2.4
linter-jade, v0.3.2
markdown-preview-plus, v2.2.2
source-preview-jade, v0.1.1
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by cristian-sima** [comment]
+ 1


```
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.3
**System**: Microsoft Windows 10 Pro
**Thrown From**: [emmet](https://github.com/emmetio/emmet-atom) package, v2.4.3


### Stack Trace

Uncaught TypeError: Cannot read property 'path' of null

```
At C:\Users\Cristian\AppData\Local\atom\app-1.7.3\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:833

TypeError: Cannot read property 'path' of null
    at Object.module.exports.getFilePath (file:///C:/Users/Cristian/.atom/packages/emmet/lib/editor-proxy.coffee:238:24)
    at encodeToBase64 (C:\Users\Cristian\.atom\packages\emmet\node_modules\emmet\lib\action\base64.js:40:27)
    at Object.encodeDecodeDataUrlAction (C:\Users\Cristian\.atom\packages\emmet\node_modules\emmet\lib\action\base64.js:131:13)
    at Object.run (C:\Users\Cristian\.atom\packages\emmet\node_modules\emmet\lib\action\main.js:150:21)
    at Object.run (C:\Users\Cristian\.atom\packages\emmet\node_modules\emmet\lib\emmet.js:81:23)
    at runAction (file:///C:/Users/Cristian/.atom/packages/emmet/lib/emmet.coffee:94:9)
    at file:///C:/Users/Cristian/.atom/packages/emmet/lib/emmet.coffee:62:9
    at Object.module.exports.exec (file:///C:/Users/Cristian/.atom/packages/emmet/lib/editor-proxy.coffee:80:10)
    at file:///C:/Users/Cristian/.atom/packages/emmet/lib/emmet.coffee:61:19
    at TextBuffer.module.exports.TextBuffer.transact (C:\Users\Cristian\AppData\Local\atom\app-1.7.3\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:828:18)
    at TextEditor.module.exports.TextEditor.transact (C:\Users\Cristian\AppData\Local\atom\app-1.7.3\resources\app.asar\src\text-editor.js:1274:26)
    at atom-text-editor.<anonymous> (file:///C:/Users/Cristian/.atom/packages/emmet/lib/emmet.coffee:60:24)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Cristian\AppData\Local\atom\app-1.7.3\resources\app.asar\src\command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (C:\Users\Cristian\AppData\Local\atom\app-1.7.3\resources\app.asar\src\command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\Cristian\AppData\Local\atom\app-1.7.3\resources\app.asar\src\command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (C:\Users\Cristian\AppData\Local\atom\app-1.7.3\resources\app.asar\src\atom-environment.js:1100:28)
    at EventEmitter.outerCallback (C:\Users\Cristian\AppData\Local\atom\app-1.7.3\resources\app.asar\src\application-delegate.js:314:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
```

### Commands

```
  3x -1:06.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:59.3.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -0:59.3.0 editor:newline (atom-text-editor.editor.is-focused)
  3x -0:58.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:56 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:56 core:cancel (atom-text-editor.editor.is-focused)
     -0:43.9.0 core:save (atom-text-editor.editor.is-focused)
     -0:42.6.0 tree-view:rename (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  3x -0:41.9.0 core:move-right (atom-text-editor.editor.mini.is-focused)
  3x -0:41.4.0 core:delete (atom-text-editor.editor.mini.is-focused)
     -0:40.9.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:39.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:32.8.0 core:save (atom-text-editor.editor.is-focused)
     -0:18.4.0 find-and-replace:show (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:17.3.0 emmet:encode-decode-data-url (atom-text-editor.editor.mini.is-focused)
     -0:14.7.0 find-and-replace:focus-next (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "spell-check",
      "language-csharp",
      "language-c",
      "language-ruby",
      "language-python",
      "language-ruby-on-rails",
      "atom-minify",
      "linter-jshint",
      "environment",
      "css-clean"
    ],
    "packagesWithKeymapsDisabled": [
      "spell-check",
      "markdown-preview-plus",
      "atom-minify",
      "highlight-line",
      "tree-view",
      "linter",
      "linter-sass-lint"
    ],
    "themes": [
      "atom-light-ui",
      "one-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
auto-indent, v0.5.0
autocomplete-go, v1.0.8
builder-go, v1.0.0
docblockr, v0.7.3
emmet, v2.4.3
file-icons, v1.7.8
go-config, v1.1.4
go-get, v1.0.3
go-plus, v4.1.0
gofmt, v1.1.6
gometalinter-linter, v1.1.0
gorename, v1.0.2
highlight-selected, v0.11.2
language-babel, v2.18.5
linter, v1.11.4
linter-csslint, v1.3.2
linter-sass-lint, v1.4.2
markdown-preview-plus, v2.4.0
navigator-godef, v1.0.3
pigments, v0.26.0
source-preview-babel, v0.1.1
tester-go, v1.0.4

# Dev
No dev packages
```


```

**Comment by MichaelHazani** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.11.2
**Electron Version**: 0.37.8
**System**: Microsoft Windows 10 Home
**Thrown From**: [emmet](https://github.com/emmetio/emmet-atom) package, v2.4.3


### Stack Trace

Uncaught TypeError: Cannot read property 'path' of null

```
At C:\Users\micha\AppData\Local\atom\app-1.11.2\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:871

TypeError: Cannot read property 'path' of null
    at Object.module.exports.getFilePath (file:///C:/Users/micha/.atom/packages/emmet/lib/editor-proxy.coffee:238:24)
    at encodeToBase64 (C:\Users\micha\.atom\packages\emmet\node_modules\emmet\lib\action\base64.js:40:27)
    at Object.encodeDecodeDataUrlAction (C:\Users\micha\.atom\packages\emmet\node_modules\emmet\lib\action\base64.js:143:13)
    at Object.run (C:\Users\micha\.atom\packages\emmet\node_modules\emmet\lib\action\main.js:150:21)
    at Object.run (C:\Users\micha\.atom\packages\emmet\node_modules\emmet\lib\emmet.js:81:23)
    at runAction (file:///C:/Users/micha/.atom/packages/emmet/lib/emmet.coffee:94:9)
    at file:///C:/Users/micha/.atom/packages/emmet/lib/emmet.coffee:62:9
    at Object.module.exports.exec (file:///C:/Users/micha/.atom/packages/emmet/lib/editor-proxy.coffee:80:10)
    at file:///C:/Users/micha/.atom/packages/emmet/lib/emmet.coffee:61:19
    at TextBuffer.module.exports.TextBuffer.transact (C:\Users\micha\AppData\Local\atom\app-1.11.2\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:866:18)
    at TextEditor.module.exports.TextEditor.transact (C:\Users\micha\AppData\Local\atom\app-1.11.2\resources\app.asar\src\text-editor.js:1519:26)
    at atom-text-editor.<anonymous> (file:///C:/Users/micha/.atom/packages/emmet/lib/emmet.coffee:60:24)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\micha\AppData\Local\atom\app-1.11.2\resources\app.asar\src\command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (C:\Users\micha\AppData\Local\atom\app-1.11.2\resources\app.asar\src\command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\micha\AppData\Local\atom\app-1.11.2\resources\app.asar\src\command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (C:\Users\micha\AppData\Local\atom\app-1.11.2\resources\app.asar\src\atom-environment.js:1127:28)
    at EventEmitter.outerCallback (C:\Users\micha\AppData\Local\atom\app-1.11.2\resources\app.asar\src\application-delegate.js:341:25)
    at emitTwo (events.js:100:13)
    at EventEmitter.emit (events.js:185:7)
```

### Commands

```
     -2:12.1.0 application:add-project-folder (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -1:58.3.0 core:save-as (atom-pane.pane.active)
     -1:56.1.0 application:new-file (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -1:47.2.0 find-and-replace:use-selection-as-find-pattern (atom-text-editor.editor.is-focused)
     -1:45.8.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -1:45.8.0 core:cancel (atom-text-editor.editor.mini.is-focused)
  7x -0:17.9.0 find-and-replace:use-selection-as-find-pattern (atom-text-editor.editor.is-focused)
     -0:13 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:13 core:cancel (atom-text-editor.editor.is-focused)
     -0:11.6.0 find-and-replace:use-selection-as-find-pattern (atom-text-editor.editor.is-focused)
     -0:03.0 emmet:encode-decode-data-url (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "telemetryConsent": "no",
    "themes": [
      "hacking-the-kernel-ui",
      "eighty-shades-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
angularjs, vundefined (active)
atom-beautify, v0.29.9 (active)
atom-ternjs, v0.14.2 (active)
autoclose-html, vundefined (active)
color-picker, vundefined (active)
eighty-shades-syntax, v0.0.0 (active)
emmet, v2.4.3 (active)
file-icons, v1.7.17 (active)
git-plus, v5.16.2 (inactive)
hacking-the-kernel, v1.6.1 (inactive)
hacking-the-kernel-ui, v1.5.0 (active)
javascript-snippets, vundefined (active)
linter, v1.11.14 (active)
minimap, v4.24.7 (active)
oceanic-next, vundefined (active)
open-recent, v5.0.0 (active)
pigments, v0.31.2 (active)
sync-settings, v0.7.2 (active)
todo-show, vundefined (active)
tool-bar, vundefined (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (inactive)
one-light-ui, v1.6.0 (inactive)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.201.1 (active)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.59.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v1.0.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2-hotfix1 (active)
snippets, v1.0.2 (active)
spell-check, v0.68.2 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.209.3 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```
