### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by renatorib** [emmetio/emmet-atom#379]
[Enter steps to reproduce below:]

1. typed `.class[]` 
2. trigged tab

**Atom Version**: 1.3.2
**System**: Mac OS X 10.10.4
**Thrown From**: [emmet](https://github.com/emmetio/emmet-atom) package, v2.3.17

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:803

TypeError: Cannot read property 'length' of undefined
    at Object.replaceUnescapedSymbol (/Users/macbook/.atom/packages/emmet/node_modules/emmet/lib/utils/common.js:192:16)
    at /Users/macbook/.atom/packages/emmet/node_modules/emmet/lib/parser/processor/attributes.js:49:26
    at Array.forEach (native)
    at resolveDefaultAttrs (/Users/macbook/.atom/packages/emmet/node_modules/emmet/lib/parser/processor/attributes.js:29:17)
    at Object.preprocessor (/Users/macbook/.atom/packages/emmet/node_modules/emmet/lib/parser/processor/attributes.js:78:4)
    at /Users/macbook/.atom/packages/emmet/node_modules/emmet/lib/parser/abbreviation.js:916:5
    at Array.forEach (native)
    at Object.parse (/Users/macbook/.atom/packages/emmet/node_modules/emmet/lib/parser/abbreviation.js:915:18)
    at Object.expand (/Users/macbook/.atom/packages/emmet/node_modules/emmet/lib/parser/abbreviation.js:957:26)
    at Object.handlers.add.order [as fn] (/Users/macbook/.atom/packages/emmet/node_modules/emmet/lib/action/expandAbbreviation.js:65:25)
    at /Users/macbook/.atom/packages/emmet/node_modules/emmet/lib/assets/handlerList.js:93:19
    at /Users/macbook/.atom/packages/emmet/node_modules/emmet/lib/utils/common.js:600:10
    at Array.some (native)
    at Object.find (/Users/macbook/.atom/packages/emmet/node_modules/emmet/lib/utils/common.js:599:9)
    at Object.HandlerList.exec (/Users/macbook/.atom/packages/emmet/node_modules/emmet/lib/assets/handlerList.js:92:10)
    at Object.expandAbbreviationAction (/Users/macbook/.atom/packages/emmet/node_modules/emmet/lib/action/expandAbbreviation.js:110:20)
    at Object.expandAbbreviationWithTabAction (/Users/macbook/.atom/packages/emmet/node_modules/emmet/lib/action/expandAbbreviation.js:140:14)
    at Object.run (/Users/macbook/.atom/packages/emmet/node_modules/emmet/lib/action/main.js:150:21)
    at Object.run (/Users/macbook/.atom/packages/emmet/node_modules/emmet/lib/emmet.js:81:23)
    at runAction (/Users/macbook/.atom/packages/emmet/lib/emmet.coffee:94:9)
    at /Users/macbook/.atom/packages/emmet/lib/emmet.coffee:62:9
    at Object.module.exports.exec (/Users/macbook/.atom/packages/emmet/lib/editor-proxy.coffee:80:10)
    at /Users/macbook/.atom/packages/emmet/lib/emmet.coffee:61:19
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:798:18)
    at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1202:26)
    at atom-text-editor.<anonymous> (/Users/macbook/.atom/packages/emmet/lib/emmet.coffee:60:24)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
```

### Commands

```
     -0:10.9.0 emmet:expand-abbreviation-with-tab (atom-text-editor.editor.is-focused)
     -0:10.2.0 core:undo (atom-text-editor.editor.is-focused)
     -0:09.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:09.3.0 emmet:expand-abbreviation-with-tab (atom-text-editor.editor.is-focused)
     -0:08.8.0 core:undo (atom-text-editor.editor.is-focused)
     -0:08.2.0 emmet:expand-abbreviation-with-tab (atom-text-editor.editor.is-focused)
     -0:07.7.0 core:undo (atom-text-editor.editor.is-focused)
     -0:07.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:06.6.0 emmet:expand-abbreviation-with-tab (atom-text-editor.editor.is-focused)
     -0:06.0 core:undo (atom-text-editor.editor.is-focused)
     -0:05.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:05.2.0 emmet:expand-abbreviation-with-tab (atom-text-editor.editor.is-focused)
     -0:04.5.0 core:undo (atom-text-editor.editor.is-focused)
     -0:04.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:03.4.0 core:move-right (atom-text-editor.editor.is-focused)
  2x -0:03.2.0 emmet:expand-abbreviation-with-tab (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "native-ui",
      "bleen-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
bleen-syntax, v0.1.0
emmet, v2.3.17
language-ejs, v0.2.0
language-vue, v0.8.0
native-ui, v0.10.0

# Dev
No dev packages
```

**Comment by cristian-sima** [comment]
[] and then tab

**Comment by cristian-sima** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Microsoft Windows 10 Pro
**Thrown From**: [emmet](https://github.com/emmetio/emmet-atom) package, v2.4.3


### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At C:\Users\Cristian\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:833

TypeError: Cannot read property 'length' of undefined
    at Object.replaceUnescapedSymbol (C:\Users\Cristian\.atom\packages\emmet\node_modules\emmet\lib\utils\common.js:192:16)
    at C:\Users\Cristian\.atom\packages\emmet\node_modules\emmet\lib\parser\processor\attributes.js:49:26
    at Array.forEach (native)
    at resolveDefaultAttrs (C:\Users\Cristian\.atom\packages\emmet\node_modules\emmet\lib\parser\processor\attributes.js:29:17)
    at Object.preprocessor (C:\Users\Cristian\.atom\packages\emmet\node_modules\emmet\lib\parser\processor\attributes.js:78:4)
    at C:\Users\Cristian\.atom\packages\emmet\node_modules\emmet\lib\parser\abbreviation.js:916:5
    at Array.forEach (native)
    at Object.parse (C:\Users\Cristian\.atom\packages\emmet\node_modules\emmet\lib\parser\abbreviation.js:915:18)
    at Object.expand (C:\Users\Cristian\.atom\packages\emmet\node_modules\emmet\lib\parser\abbreviation.js:957:26)
    at Object.handlers.add.order [as fn] (C:\Users\Cristian\.atom\packages\emmet\node_modules\emmet\lib\action\expandAbbreviation.js:65:25)
    at C:\Users\Cristian\.atom\packages\emmet\node_modules\emmet\lib\assets\handlerList.js:93:19
    at C:\Users\Cristian\.atom\packages\emmet\node_modules\emmet\lib\utils\common.js:600:10
    at Array.some (native)
    at Object.find (C:\Users\Cristian\.atom\packages\emmet\node_modules\emmet\lib\utils\common.js:599:9)
    at Object.HandlerList.exec (C:\Users\Cristian\.atom\packages\emmet\node_modules\emmet\lib\assets\handlerList.js:92:10)
    at Object.expandAbbreviationAction (C:\Users\Cristian\.atom\packages\emmet\node_modules\emmet\lib\action\expandAbbreviation.js:110:20)
    at Object.expandAbbreviationWithTabAction (C:\Users\Cristian\.atom\packages\emmet\node_modules\emmet\lib\action\expandAbbreviation.js:140:14)
    at Object.run (C:\Users\Cristian\.atom\packages\emmet\node_modules\emmet\lib\action\main.js:150:21)
    at Object.run (C:\Users\Cristian\.atom\packages\emmet\node_modules\emmet\lib\emmet.js:81:23)
    at runAction (file:///C:/Users/Cristian/.atom/packages/emmet/lib/emmet.coffee:94:9)
    at file:///C:/Users/Cristian/.atom/packages/emmet/lib/emmet.coffee:62:9
    at Object.module.exports.exec (file:///C:/Users/Cristian/.atom/packages/emmet/lib/editor-proxy.coffee:80:10)
    at file:///C:/Users/Cristian/.atom/packages/emmet/lib/emmet.coffee:61:19
    at TextBuffer.module.exports.TextBuffer.transact (C:\Users\Cristian\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:828:18)
    at TextEditor.module.exports.TextEditor.transact (C:\Users\Cristian\AppData\Local\atom\app-1.8.0\resources\app.asar\src\text-editor.js:1328:26)
    at atom-text-editor.<anonymous> (file:///C:/Users/Cristian/.atom/packages/emmet/lib/emmet.coffee:60:24)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Cristian\AppData\Local\atom\app-1.8.0\resources\app.asar\src\command-registry.js:260:29)
    at C:\Users\Cristian\AppData\Local\atom\app-1.8.0\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\Cristian\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\Cristian\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (C:\Users\Cristian\AppData\Local\atom\app-1.8.0\resources\app.asar\src\window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (C:\Users\Cristian\AppData\Local\atom\app-1.8.0\resources\app.asar\src\window-event-handler.js:3:61)
```

### Commands

```
     -0:21.7.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:21.7.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:20.9.0 core:undo (atom-text-editor.editor.is-focused)
  6x -0:20.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:17.7.0 emmet:expand-abbreviation-with-tab (atom-text-editor.editor.is-focused)
     -0:17.1.0 core:undo (atom-text-editor.editor.is-focused)
     -0:16.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:15.6.0 emmet:expand-abbreviation-with-tab (atom-text-editor.editor.is-focused)
     -0:15 core:undo (atom-text-editor.editor.is-focused)
  2x -0:14.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:10.1.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:09.9.0 emmet:expand-abbreviation-with-tab (atom-text-editor.editor.is-focused)
     -0:08.2.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:07.9.0 emmet:expand-abbreviation-with-tab (atom-text-editor.editor.is-focused)
  3x -0:01.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:00.1.0 core:move-right (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "autoHideMenuBar": true,
    "disabledPackages": [
      "spell-check",
      "language-csharp",
      "language-c",
      "language-ruby",
      "language-python",
      "language-ruby-on-rails",
      "atom-minify",
      "linter-jshint",
      "environment",
      "css-clean",
      "tester-go",
      "atom-ternjs",
      "source-preview-babel",
      "source-preview",
      "linter-csslint",
      "linter-eslint"
    ],
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "._*",
      "Thumbs.db",
      "staticp"
    ],
    "packagesWithKeymapsDisabled": [
      "spell-check",
      "markdown-preview-plus",
      "atom-minify",
      "highlight-line",
      "tree-view",
      "linter",
      "linter-sass-lint"
    ],
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
auto-indent, v0.5.0
autocomplete-go, v1.1.0
autoupdate-packages, v1.3.1
builder-go, v1.0.0
docblockr, v0.7.3
emmet, v2.4.3
file-icons, v1.7.15
go-config, v1.1.4
go-get, v1.0.3
go-plus, v4.1.0
gofmt, v1.1.6
gometalinter-linter, v1.1.0
gorename, v1.0.2
highlight-selected, v0.11.2
language-babel, v2.29.2
linter, v1.11.14
linter-sass-lint, v1.6.1
markdown-preview-plus, v2.4.0
navigator-godef, v1.0.3
pigments, v0.29.3
react, v0.15.0
sync-settings, v0.7.2

# Dev
No dev packages
```
