### ISSUE TITLE
Uncaught TypeError: Cannot use 'in' operator to search for 'tag_case' in erb

### ISSUE THREAD

**Issue by kylekeesling** [emmetio/emmet-atom#391]
1. type "div.col-sm-12"
2. hit Tab
3. Boom goes the dynomite

**Atom Version**: 1.4.1
**System**: Mac OS X 10.11.2
**Thrown From**: [emmet](https://github.com/emmetio/emmet-atom) package, v2.4.1

### Stack Trace

Uncaught TypeError: Cannot use 'in' operator to search for 'tag_case' in erb

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:810

TypeError: Cannot use 'in' operator to search for 'tag_case' in erb
    at /Users/kylekeesling/Dropbox/Apps/Atom/packages/emmet/node_modules/emmet/lib/utils/common.js:639:20
    at Array.forEach (native)
    at Object.defaults (/Users/kylekeesling/Dropbox/Apps/Atom/packages/emmet/node_modules/emmet/lib/utils/common.js:638:21)
    at Object.create (/Users/kylekeesling/Dropbox/Apps/Atom/packages/emmet/node_modules/emmet/lib/assets/profile.js:210:36)
    at Object.get (/Users/kylekeesling/Dropbox/Apps/Atom/packages/emmet/node_modules/emmet/lib/assets/profile.js:242:16)
    at Object.expand (/Users/kylekeesling/Dropbox/Apps/Atom/packages/emmet/node_modules/emmet/lib/parser/abbreviation.js:953:20)
    at Object.handlers.add.order [as fn] (/Users/kylekeesling/Dropbox/Apps/Atom/packages/emmet/node_modules/emmet/lib/action/expandAbbreviation.js:65:25)
    at /Users/kylekeesling/Dropbox/Apps/Atom/packages/emmet/node_modules/emmet/lib/assets/handlerList.js:93:19
    at /Users/kylekeesling/Dropbox/Apps/Atom/packages/emmet/node_modules/emmet/lib/utils/common.js:600:10
    at Array.some (native)
    at Object.find (/Users/kylekeesling/Dropbox/Apps/Atom/packages/emmet/node_modules/emmet/lib/utils/common.js:599:9)
    at Object.HandlerList.exec (/Users/kylekeesling/Dropbox/Apps/Atom/packages/emmet/node_modules/emmet/lib/assets/handlerList.js:92:10)
    at Object.expandAbbreviationAction (/Users/kylekeesling/Dropbox/Apps/Atom/packages/emmet/node_modules/emmet/lib/action/expandAbbreviation.js:110:20)
    at Object.expandAbbreviationWithTabAction (/Users/kylekeesling/Dropbox/Apps/Atom/packages/emmet/node_modules/emmet/lib/action/expandAbbreviation.js:140:14)
    at Object.run (/Users/kylekeesling/Dropbox/Apps/Atom/packages/emmet/node_modules/emmet/lib/action/main.js:150:21)
    at Object.run (/Users/kylekeesling/Dropbox/Apps/Atom/packages/emmet/node_modules/emmet/lib/emmet.js:81:23)
    at runAction (/Volumes/Macintosh HD/Users/kylekeesling/Dropbox/Apps/atom/packages/emmet/lib/emmet.coffee:94:9)
    at /Volumes/Macintosh HD/Users/kylekeesling/Dropbox/Apps/atom/packages/emmet/lib/emmet.coffee:62:9
    at Object.module.exports.exec (/Volumes/Macintosh HD/Users/kylekeesling/Dropbox/Apps/atom/packages/emmet/lib/editor-proxy.coffee:81:10)
    at /Volumes/Macintosh HD/Users/kylekeesling/Dropbox/Apps/atom/packages/emmet/lib/emmet.coffee:61:19
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:805:18)
    at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1216:26)
    at atom-text-editor.<anonymous> (/Volumes/Macintosh HD/Users/kylekeesling/Dropbox/Apps/atom/packages/emmet/lib/emmet.coffee:60:24)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -2:43.7.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:41.8.0 emmet:expand-abbreviation-with-tab (atom-text-editor.editor.is-focused)
     -2:32.1.0 core:save (atom-text-editor.editor.is-focused)
  2x -1:42.4.0 application:hide (atom-text-editor.editor.is-focused)
     -0:18.8.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -0:18.5.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -0:18.2.0 core:cut (atom-text-editor.editor.is-focused)
  2x -0:17.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:17 core:move-to-top (atom-text-editor.editor.is-focused)
     -0:16.5.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:16.2.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:16.2.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:15.9.0 core:paste (atom-text-editor.editor.is-focused)
     -0:15.8.0 editor:newline-below (atom-text-editor.editor.is-focused)
     -0:15.4.0 core:save (atom-text-editor.editor.is-focused)
     -0:01.3.0 emmet:expand-abbreviation-with-tab (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "autocomplete",
      "color-picker"
    ],
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "projectHome": "/Users/kylekeesling/sites",
    "themes": [
      "atom-dark-ui",
      "railscast-theme"
    ]
  },
  "emmet": {}
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.5.1
editor-stats, v0.17.0
emmet, v2.4.1
railscast-theme, v0.3.0

# Dev
No dev packages
```

**Comment by fabianfiorotto** [comment]
How did you solve this?

**Comment by kylekeesling** [comment]
Actually I didn't - it stopped happening on it's own but it now pops up intermittently for no reason. If you are experiencing this too, maybe we should reopen?

**Comment by fabianfiorotto** [comment]
I have the same problem with php files. I can't expand any tag even with the most simple tag I get this error.

**Comment by kylekeesling** [comment]
Ok. It's happening to me when editing Ruby/erb. I'll go ahead and reopen.

**Comment by kylekeesling** [comment]
Still happening in Atom 1.7.1 and emmet-atom 2.4.3

**Comment by CarlosV89** [comment]
This is happening to me when I add hbs handling. 
`    "handlebars": {
        "extends": "html",
        "profile": "handlebars",
        "filters": "html"
    }
`

in the snippets.json, and adding:
`
'atom-text-editor[data-grammar="text html handlebars"]:not([mini])':
    'tab': 'emmet:expand-abbreviation-with-tab'
`
into the keymap.cson.
