### ISSUE TITLE
Uncaught Error: EISDIR: illegal operation on a directory, read

### ISSUE THREAD

**Issue by seedby** [emmetio/emmet-atom#507]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: [emmet](https://github.com/emmetio/emmet-atom) package 2.4.3

### Stack Trace

Uncaught Error: EISDIR: illegal operation on a directory, read

```
At C:\Users\Dima\AppData\Local\atom\app-1.16.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:833

Error: EISDIR: illegal operation on a directory, read
    at Error (native)
    at Object.fs.readSync (fs.js:731:19)
    at tryReadSync (fs.js:486:20)
    at Object.fs.readFileSync (fs.js:534:19)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:501:29)
    at Function._read (/packages/emmet/node_modules/emmet/lib/plugin/file.js:106:24)
    at Function.read (/packages/emmet/node_modules/emmet/lib/plugin/file.js:118:9)
    at /packages/emmet/node_modules/emmet/lib/action/base64.js:53:9
    at Function.locateFile (/packages/emmet/node_modules/emmet/lib/plugin/file.js:171:13)
    at encodeToBase64 (/packages/emmet/node_modules/emmet/lib/action/base64.js:48:8)
    at Object.encodeDecodeDataUrlAction (/packages/emmet/node_modules/emmet/lib/action/base64.js:143:13)
    at Object.run (/packages/emmet/node_modules/emmet/lib/action/main.js:150:21)
    at Object.run (/packages/emmet/node_modules/emmet/lib/emmet.js:81:23)
    at runAction (/packages/emmet/lib/emmet.coffee:94:9)
    at /packages/emmet/lib/emmet.coffee:62:9
    at Object.exec (/packages/emmet/lib/editor-proxy.coffee:80:10)
    at /packages/emmet/lib/emmet.coffee:61:19
    at TextBuffer.module.exports.TextBuffer.transact (/app.asar/node_modules/text-buffer/lib/text-buffer.js:828:18)
    at TextEditor.module.exports.TextEditor.transact (/app.asar/src/text-editor.js:1594:26)
    at /packages/emmet/lib/emmet.coffee:60:24)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -0:41.8.0 core:copy (input.hidden-input)
     -0:39.6.0 core:paste (input.hidden-input)
     -0:35 core:move-right (input.hidden-input)
     -0:33.8.0 editor:newline (input.hidden-input)
     -0:33.2.0 core:move-down (input.hidden-input)
  3x -0:33 core:move-left (input.hidden-input)
     -0:32.1.0 editor:select-to-end-of-line (input.hidden-input)
     -0:32.1.0 core:select-left (input.hidden-input)
     -0:31.7.0 core:delete (input.hidden-input)
     -0:28.5.0 core:move-up (input.hidden-input)
     -0:21.8.0 editor:newline (input.hidden-input)
  2x -0:15.7.0 core:backspace (input.hidden-input)
     -0:13.8.0 editor:select-to-beginning-of-word (input.hidden-input)
  2x -0:13 editor:toggle-line-comments (input.hidden-input)
     -0:10.8.0 emmet:encode-decode-data-url (input.hidden-input)
     -0:00.3.0 editor:select-to-beginning-of-word (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.29.17 
auto-encoding 0.6.3 
base16-ocean-dark-syntax-theme 0.1.10 
color-picker 2.2.5 
copy-filename 1.0.1 
emmet 2.4.3 
file-icons 2.1.1 
filesize 2.0.4 
git-control 0.8.2 
highlight-selected 0.12.0 
javascript-snippets 1.2.1 
keybinding-cheatsheet 0.1.1 
language-perl-template-toolkit 0.1.0 
linter 2.1.0 
linter-jscs 4.1.2 
linter-jshint 3.0.3 
minimap 4.26.8 
pdf-view 0.56.0 
pigments 0.39.1 
platformio-ide-terminal 2.5.0 
prime-file-icons 0.3.0 
project-viewer 1.0.12 
prompt-big-file 0.3.0 
qolor 0.4.1 
react 0.16.2 
react-redux-atom-snippets 0.7.2 
spacegray-atom-dark-syntax 1.3.2 
svn 0.0.13 
sync-settings 0.8.1 
todo-show 1.11.0 
```

**Comment by DWPanda** [comment]
getEnemy.innerHTML = '<img src="img/avatar-enemies/' + enemy.enemyType.toLowerCase() + '.png" class="img-avatar"><div><h3>' + enemy.enemyType + '</h3><p>Health: ' + enemy.health + '</p><p>Mana: ' + enemy.mana + '</p><p>Strength: ' + enemy.strength + '</p><p>Agility: ' + enemy.agility + '</p><p>Speed: ' + enemy.speed + '</p></div>';

**Comment by DWPanda** [comment]
"uncaught error: EISDIR: illegal operation on a directory, read"
<embedded>: 11

I've been working on this tutorial from this 3-part video on youtube and i am STUCK on this code error... and idk why. I've re-typed it from scratch 20+ times, commented on creator's channel video half a dozen times. i've posted on 2 fb groups several times.

i can not get this code to work. I don't know if it's syntax, spelling, or what but when i open index.html, EVERYTHING else works until i get to "find an enemy" where it's supposed to pull up a new screen showcasing the class i picked (img of class with stats on top, img of 1 out of 2 possible enemies with their stats below) and instead it gives me this error:

getEnemy.innerHTML = '<img src="img/avatar-enemies/' + enemy.enemyType.toLowerCase() + '.png" alt="' + enemy.enemyType + '" class="img-avatar"><div><h3>' + enemy.enemyType + '</h3><p class="health-enemy">Health: ' + enemy.health + '</p><p>Mana: ' + enemy.mana + '</p><p>Strength: ' + enemy.strength + '</p><p>Agility: ' + enemy.agility + '</p><p>Speed: ' + enemy.speed + '</p></div>';

"uncaught TypeError: cannot set property 'innerHTML' of null"
....
