### ISSUE TITLE
Failed to load the emmet package

### ISSUE THREAD

**Issue by jyy1996** [emmetio/emmet-atom#512]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Unknown Windows version
**Thrown From**: [emmet](https://github.com/emmetio/emmet-atom) package 2.4.3

### Stack Trace

Failed to load the emmet package

```
At Cannot find module 'emmet'

Error: Cannot find module 'emmet'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.17.2/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.17.2/resources/app/src/module-cache.js:354:1)
    at Module.require (~/AppData/Local/atom/app-1.17.2/resources/app/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.17.2/resources/app/src/native-compile-cache.js:66:1)
    at /packages/emmet-atom/lib/emmet.coffee:5:9)
    at /packages/emmet-atom/lib/emmet.coffee:1:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.17.2/resources/app/src/native-compile-cache.js:106:1)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.17.2/resources/app/src/compile-cache.js:230:1)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (~/AppData/Local/atom/app-1.17.2/resources/app/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (~/AppData/Local/atom/app-1.17.2/resources/app/static/<embedded>:73:1)
    at Package.module.exports.Package.requireMainModule (~/AppData/Local/atom/app-1.17.2/resources/app/src/package.js:887:1)
    at ~/AppData/Local/atom/app-1.17.2/resources/app/src/package.js:158:1
    at Package.module.exports.Package.measure (~/AppData/Local/atom/app-1.17.2/resources/app/src/package.js:99:1)
    at Package.module.exports.Package.load (~/AppData/Local/atom/app-1.17.2/resources/app/src/package.js:144:1)
    at PackageManager.module.exports.PackageManager.loadAvailablePackage (~/AppData/Local/atom/app-1.17.2/resources/app/src/package-manager.js:562:1)
    at ~/AppData/Local/atom/app-1.17.2/resources/app/src/package-manager.js:476:1
    at Config.module.exports.Config.transact (~/AppData/Local/atom/app-1.17.2/resources/app/src/config.js:321:1)
    at PackageManager.module.exports.PackageManager.loadPackages (~/AppData/Local/atom/app-1.17.2/resources/app/src/package-manager.js:470:1)
    at ~/AppData/Local/atom/app-1.17.2/resources/app/src/atom-environment.js:798:1
```

### Commands

```
  4x -0:59.9.0 core:copy (atom-pane.pane.active)
```

### Non-Core Packages

```
atom-ternjs 0.18.3 
emmet 2.4.3 
language-vue 0.22.0 
language-vue-component 0.5.0 
markdown-writer 2.6.5 
vue2-autocomplete 0.1.0-alpha.4 
```

**Comment by sergeche** [comment]
Plugin wasn’t installed correctly, please reinstall
