### ISSUE TITLE
Uncaught TypeError: Cannot read property 'children' of undefined

### ISSUE THREAD

**Issue by DrShpongle** [emmetio/emmet-atom#525]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [emmet](https://github.com/emmetio/emmet-atom) package 2.4.3

### Stack Trace

Uncaught TypeError: Cannot read property 'children' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:854

TypeError: Cannot read property 'children' of undefined
    at /packages/emmet/node_modules/emmet/lib/filter/singleLine.js:16:7)
    at /packages/emmet/node_modules/emmet/lib/filter/main.js:72:36
    at Array.forEach (native)
    at Object.apply (/packages/emmet/node_modules/emmet/lib/filter/main.js:69:18)
    at Object.expand (/packages/emmet/node_modules/emmet/lib/parser/abbreviation.js:960:12)
    at /packages/emmet/node_modules/emmet/lib/action/expandAbbreviation.js:65:25)
    at /packages/emmet/node_modules/emmet/lib/assets/handlerList.js:93:19
    at /packages/emmet/node_modules/emmet/lib/utils/common.js:600:10
    at Array.some (native)
    at Object.find (/packages/emmet/node_modules/emmet/lib/utils/common.js:599:9)
    at Object.exec (/packages/emmet/node_modules/emmet/lib/assets/handlerList.js:92:10)
    at Object.expandAbbreviationAction (/packages/emmet/node_modules/emmet/lib/action/expandAbbreviation.js:110:20)
    at Object.run (/packages/emmet/node_modules/emmet/lib/action/main.js:150:21)
    at Object.run (/packages/emmet/node_modules/emmet/lib/emmet.js:81:23)
    at runAction (/packages/emmet/lib/emmet.coffee:94:9)
    at /packages/emmet/lib/emmet.coffee:62:9
    at Object.exec (/packages/emmet/lib/editor-proxy.coffee:80:10)
    at /packages/emmet/lib/emmet.coffee:61:19
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:849:24)
    at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1599:32)
    at /packages/emmet/lib/emmet.coffee:60:24)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:35)
    at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -6:30.2.0 autocomplete-plus:confirm (input.hidden-input)
     -6:23 core:save (input.hidden-input)
     -4:14.5.0 core:backspace (input.hidden-input)
     -4:12.2.0 core:save (input.hidden-input)
     -1:03.6.0 editor:newline (input.hidden-input)
  3x -1:02.0 core:backspace (input.hidden-input)
     -1:00.5.0 core:move-up (input.hidden-input)
     -1:00.2.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -1:00.0 editor:newline (input.hidden-input)
     -0:53.4.0 core:save (input.hidden-input)
     -0:22 editor:newline (input.hidden-input)
     -0:19.7.0 snippets:next-tab-stop (input.hidden-input)
     -0:19.7.0 snippets:expand (input.hidden-input)
     -0:19.7.0 editor:indent (input.hidden-input)
  2x -0:18.7.0 core:backspace (input.hidden-input)
     -0:15.9.0 emmet:expand-abbreviation (input.hidden-input)
```

### Non-Core Packages

```
atom-tachyons 1.6.0 
busy-signal 1.4.3 
emmet 2.4.3 
emmet-jsx-css-modules 1.0.0 
file-icons 2.1.9 
git-plus 7.9.3 
hyperclick 0.1.2 
intentions 1.1.2 
js-hyperclick 1.11.0 
language-babel 2.67.0 
linter 2.2.0 
linter-ui-default 1.6.2 
merge-conflicts 1.4.5 
pigments 0.39.1 
platformio-ide-terminal 2.5.3 
```

**Comment by Lwenli1224** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.2
**Thrown From**: [emmet](https://github.com/emmetio/emmet-atom) package 2.4.3


### Stack Trace

Uncaught TypeError: Cannot read property 'children' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:948

TypeError: Cannot read property 'children' of undefined
    at /packages/emmet/node_modules/emmet/lib/filter/singleLine.js:16:7)
    at /packages/emmet/node_modules/emmet/lib/filter/main.js:72:36
    at Array.forEach (native)
    at Object.apply (/packages/emmet/node_modules/emmet/lib/filter/main.js:69:18)
    at Object.expand (/packages/emmet/node_modules/emmet/lib/parser/abbreviation.js:960:12)
    at /packages/emmet/node_modules/emmet/lib/action/expandAbbreviation.js:65:25)
    at /packages/emmet/node_modules/emmet/lib/assets/handlerList.js:93:19
    at /packages/emmet/node_modules/emmet/lib/utils/common.js:600:10
    at Array.some (native)
    at Object.find (/packages/emmet/node_modules/emmet/lib/utils/common.js:599:9)
    at HandlerList.exec (/packages/emmet/node_modules/emmet/lib/assets/handlerList.js:92:10)
    at Object.expandAbbreviationAction (/packages/emmet/node_modules/emmet/lib/action/expandAbbreviation.js:110:20)
    at Object.expandAbbreviationWithTabAction (/packages/emmet/node_modules/emmet/lib/action/expandAbbreviation.js:140:14)
    at Object.run (/packages/emmet/node_modules/emmet/lib/action/main.js:150:21)
    at Object.run (/packages/emmet/node_modules/emmet/lib/emmet.js:81:23)
    at runAction (/packages/emmet/lib/emmet.coffee:94:9)
    at /packages/emmet/lib/emmet.coffee:62:9
    at Object.exec (/packages/emmet/lib/editor-proxy.coffee:80:10)
    at /packages/emmet/lib/emmet.coffee:61:19
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:941:24)
    at TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1811:30)
    at /packages/emmet/lib/emmet.coffee:60:24)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:388:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:108:40)
```

### Commands

```
     -2:35.1.0 docblockr:parse-enter (input.hidden-input)
     -2:35.1.0 editor:newline (input.hidden-input)
  4x -2:31.4.0 core:backspace (input.hidden-input)
     -2:15.2.0 core:move-left (input.hidden-input)
     -2:14.9.0 core:move-right (input.hidden-input)
     -2:13.2.0 core:backspace (input.hidden-input)
     -2:10.9.0 core:move-right (input.hidden-input)
  2x -2:09.9.0 core:save (input.hidden-input)
     -1:29.5.0 core:move-right (input.hidden-input)
  6x -1:29.1.0 core:backspace (input.hidden-input)
     -1:27.2.0 core:save (input.hidden-input)
     -1:12.1.0 editor:duplicate-lines (input.hidden-input)
     -1:11.1.0 emmet:toggle-comment (input.hidden-input)
     -1:11.1.0 editor:toggle-line-comments (input.hidden-input)
     -1:08.2.0 core:backspace (input.hidden-input)
     -1:04.8.0 emmet:expand-abbreviation-with-tab (input.hidden-input)
```

### Non-Core Packages

```
1989-syntax 0.5.0 
activate-power-mode 2.6.0 
atom-beautify 0.30.9 
atom-ide-ui 0.7.0 
atom-jshint 2.0.0 
atom-live-server 2.2.0 
atom-material-syntax 1.0.7 
atom-material-ui 2.0.6 
atom-react-autocomplete 0.1.10 
atom-ternjs 0.18.3 
atom-visual-studio-code-ui 1.3.4 
autoclose-html 0.23.0 
autocomplete-html-entities 0.2.0 
autocomplete-js-import 1.4.0 
autocomplete-paths 2.12.1 
autoprefixer 3.7.1 
block-comment 0.4.3 
browser-plus 0.0.98 
busy-signal 1.4.3 
chester-atom-syntax 0.3.0 
chester-kh-syntax 0.4.2 
color-picker 2.2.5 
comment 0.6.1 
csslint 1.2.0 
darkula-ui 0.1.0 
docblockr 0.13.4 
emmet 2.4.3 
emmet-jsx-css-modules 1.0.0 
evangelism-syntax 0.13.0 
file-icons 2.1.15 
firewatch-syntax 1.1.1 
git-control 0.9.0 
git-plus 7.10.0 
gloom 0.6.4 
goto-definition 1.3.4 
hyperclick 0.0.0 
ide-typescript 0.7.2 
improved-chester-atom-syntax 0.3.0 
intellij-idea-keymap 0.2.3 
javascript-snippets 1.2.1 
jquery-snippets 11.0.0 
js-hyperclick 1.12.2 
jshint 1.8.6 
language-babel 2.80.3 
language-javascript-jsx 0.3.7 
language-stylus 0.2.0 
language-vue 0.23.1 
linter 2.2.0 
linter-csslint 2.0.0 
linter-eslint 8.4.0 
linter-jshint 3.1.6 
linter-ui-default 1.6.10 
minimap 4.29.7 
minimap-quick-highlight 1.0.1 
monokai 0.24.0 
nord-atom-ui 0.11.0 
one-dark-vivid-syntax 1.8.0 
one-sharp-syntax 3.0.0 
open-html-in-browser 0.2.1 
open-in-browser 0.5.2 
package-sync 1.1.0 
pdf-view 0.61.0 
pigments 0.40.2 
platformio-ide-terminal 2.7.0 
prettier-atom 0.43.1 
project-manager 3.3.5 
quick-highlight 0.12.0 
react 0.17.0 
react-es6-snippets 0.3.0 
react-redux-atom-snippets 0.7.2 
react-snippets 1.0.1 
script 3.17.3 
set-syntax 0.4.0 
seti-syntax 1.1.3 
seti-ui 1.9.0 
Stylus 3.1.1 
sublime-block-comment 0.5.1 
tool-bar 1.1.0 
tool-bar-main 0.0.10 
vue-element-ui-snippets 0.7.0 
vue2-autocomplete 0.1.0-alpha.4 
vuejs2-snippets 0.15.0 
```
