### ISSUE TITLE
Failed to load the emmet package

### ISSUE THREAD

**Issue by witeyou** [emmetio/emmet-atom#537]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.20.1 x64
**Electron**: 1.6.9
**OS**: Unknown Windows version
**Thrown From**: [emmet](https://github.com/emmetio/emmet-atom) package 2.4.3

### Stack Trace

Failed to load the emmet package

```
At Cannot find module 'emmet'

Error: Cannot find module 'emmet'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.20.1/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.20.1/resources/app/src/module-cache.js:354:58)
    at Module.require (~/AppData/Local/atom/app-1.20.1/resources/app/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.20.1/resources/app/src/native-compile-cache.js:66:33)
    at /packages/emmet-atom/lib/emmet.coffee:5:9)
    at /packages/emmet-atom/lib/emmet.coffee:1:1)
    at /packages/emmet-atom/lib/emmet.coffee:1:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.20.1/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.20.1/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (~/AppData/Local/atom/app-1.20.1/resources/app/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (~/AppData/Local/atom/app-1.20.1/resources/app/static/<embedded>:96:26)
    at Package.module.exports.Package.requireMainModule (~/AppData/Local/atom/app-1.20.1/resources/app/src/package.js:887:35)
    at ~/AppData/Local/atom/app-1.20.1/resources/app/src/package.js:158:34
    at Package.module.exports.Package.measure (~/AppData/Local/atom/app-1.20.1/resources/app/src/package.js:99:21)
    at Package.module.exports.Package.load (~/AppData/Local/atom/app-1.20.1/resources/app/src/package.js:144:18)
    at PackageManager.module.exports.PackageManager.loadAvailablePackage (~/AppData/Local/atom/app-1.20.1/resources/app/src/package-manager.js:565:22)
    at ~/AppData/Local/atom/app-1.20.1/resources/app/src/package-manager.js:479:25
    at Config.module.exports.Config.transact (~/AppData/Local/atom/app-1.20.1/resources/app/src/config.js:342:22)
    at PackageManager.module.exports.PackageManager.loadPackages (~/AppData/Local/atom/app-1.20.1/resources/app/src/package-manager.js:473:25)
    at ~/AppData/Local/atom/app-1.20.1/resources/app/src/atom-environment.js:810:34
```

### Commands

```
     -0:33.4.0 markdown-preview:toggle (a.btn-issue.btn.btn-error.opening)
```

### Non-Core Packages

```
emmet 2.4.3 
```

**Comment by r3xn9** [comment]
i've got the same issue

**Comment by PanMartinez** [comment]
how to fix it ?

**Comment by inyoeye** [comment]
how to deal with it?

**Comment by joey998** [comment]
what's wrong?

**Comment by MiNiYuYu** [comment]
how to fix it?

**Comment by natwildapricot** [comment]
the same

**Comment by Mohamed-web** [comment]
the same issue

**Comment by l1veIn** [comment]
```
cd ~/.atom/packages
git clone https://github.com/emmetio/emmet-atom
cd emmet-atom
npm install
```
..I just copy these from README

**Comment by ochedenis** [comment]
fix this by typing: "npm install" on console (~ / .atom / packages / emmet-atom (from this directory))
at installing was mistake, and console recommended to use another command
