### ISSUE TITLE
Failed to activate the activate-power-mode package

### ISSUE THREAD

**Issue by VertexC** [emmetio/emmet-atom#541]
[Enter steps to reproduce below:]

1. download the package activate-power-mode

**Atom Version**: 0.187.0
**System**: Unknown Windows Version
**Thrown From**: [emmet](https://github.com/emmetio/emmet-atom) package, v2.4.3

### Stack Trace

Failed to activate the activate-power-mode package

```
At requestIdleCallback is not defined

ReferenceError: requestIdleCallback is not defined
  at Object.module.exports.ActivatePowerMode.activate (C:\Users\Administrator.WIN-4SBD3CPGOAO\.atom\packages\activate-power-mode\lib\activate-power-mode.coffee:14:5)
  at Package.module.exports.Package.activateNow (D:\atom-windows\Atom\resources\app\src\package.js:240:19)
  at D:\atom-windows\Atom\resources\app\src\package.js:221:30
  at Package.module.exports.Package.measure (D:\atom-windows\Atom\resources\app\src\package.js:167:15)
  at Package.module.exports.Package.activate (D:\atom-windows\Atom\resources\app\src\package.js:214:14)
  at PackageManager.module.exports.PackageManager.activatePackage (D:\atom-windows\Atom\resources\app\src\package-manager.js:465:21)
  at D:\atom-windows\Atom\resources\app\src\package-manager.js:334:19
  at D:\atom-windows\Atom\resources\app\src\config.js:640:20
  at Emitter.module.exports.Emitter.emit (D:\atom-windows\Atom\resources\app\node_modules\event-kit\lib\emitter.js:82:11)
  at Config.module.exports.Config.emitChangeEvent (D:\atom-windows\Atom\resources\app\src\config.js:804:29)
  at Config.module.exports.Config.setRawValue (D:\atom-windows\Atom\resources\app\src\config.js:617:19)
  at Config.module.exports.Config.set (D:\atom-windows\Atom\resources\app\src\config.js:231:14)
  at Config.module.exports.Config.removeAtKeyPath (D:\atom-windows\Atom\resources\app\src\config.js:409:12)
  at Package.module.exports.Package.enable (D:\atom-windows\Atom\resources\app\src\package.js:152:26)
  at PackageManager.module.exports.PackageManager.enablePackage (D:\atom-windows\Atom\resources\app\src\package-manager.js:162:14)
  at HTMLButtonElement.<anonymous> (D:\atom-windows\Atom\resources\app\node_modules\settings-view\lib\package-card.js:209:27)
  at HTMLButtonElement.jQuery.event.dispatch (D:\atom-windows\Atom\resources\app\node_modules\jquery\dist\jquery.js:4430:9)
  at HTMLButtonElement.elemData.handle (D:\atom-windows\Atom\resources\app\node_modules\jquery\dist\jquery.js:4116:28)

```

### Commands

```
     -2:44.6 core:undo (atom-text-editor.editor)
 12x -2:43.8 core:backspace (atom-text-editor.editor)
     -2:38.8 emmet:expand-abbreviation-with-tab (atom-text-editor.editor)
     -2:38.1 core:undo (atom-text-editor.editor)
  2x -2:37.4 core:backspace (atom-text-editor.editor)
     -2:36.5 emmet:expand-abbreviation-with-tab (atom-text-editor.editor)
  2x -2:36.2 core:backspace (atom-text-editor.editor)
     -2:35.6 core:cut (atom-text-editor.editor)
  3x -2:35.6 core:undo (atom-text-editor.editor)
  2x -2:34.3 core:backspace (atom-text-editor.editor)
     -2:27.7 emmet:expand-abbreviation-with-tab (atom-text-editor.editor)
     -1:07.5 settings-view:install-packages-and-themes (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:56.8 core:confirm (atom-text-editor.editor.mini)
     -0:53.7 core:cut (atom-text-editor.editor.mini)
     -0:51.2 core:paste (atom-text-editor.editor.mini)
     -0:48.6 core:confirm (atom-text-editor.editor.mini)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  }
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v2.6.0
emmet, v2.4.3
file-type-icons, v1.3.4

# Dev
No dev packages
```

**Comment by zpcalan** [comment]
Is this issue resolved?
