### ISSUE TITLE
Uncaught ParseError: CSS parsing error at line 2, char 5: Unrecognized character ' '      border...

### ISSUE THREAD

**Issue by lispwu** [emmetio/emmet-atom#545]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: Unknown Windows version
**Thrown From**: [emmet](https://github.com/emmetio/emmet-atom) package 2.4.3

### Stack Trace

Uncaught ParseError: CSS parsing error at line 2, char 5: Unrecognized character ' '
      border:5px solid red;
----^

```
At C:\Users\ll\AppData\Local\atom\app-1.22.1\resources\app\node_modules\text-buffer\lib\text-buffer.js:959

ParseError: CSS parsing error at line 2, char 5: Unrecognized character ' '
      border:5px solid red;
----^
    at raiseError (/packages/emmet/node_modules/emmet/lib/parser/css.js:111:16)
    at tokenize (/packages/emmet/node_modules/emmet/lib/parser/css.js:371:3)
    at Object.lex (/packages/emmet/node_modules/emmet/lib/parser/css.js:389:6)
    at Object.parse (/packages/emmet/node_modules/emmet/lib/parser/css.js:407:22)
    at extractPropertiesFromSource (/packages/emmet/node_modules/emmet/lib/editTree/css.js:246:26)
    at consumeProperties (/packages/emmet/node_modules/emmet/lib/editTree/css.js:217:14)
    at child.initialize (/packages/emmet/node_modules/emmet/lib/editTree/css.js:316:4)
    at child.EditContainer (/packages/emmet/node_modules/emmet/lib/editTree/base.js:66:19)
    at /packages/emmet/node_modules/emmet/lib/vendor/klass.js:35:12)
    at Object.parse (/packages/emmet/node_modules/emmet/lib/editTree/css.js:550:11)
    at Object.parseFromPosition (/packages/emmet/node_modules/emmet/lib/editTree/css.js:566:16)
    at Object.propertyFromPosition (/packages/emmet/node_modules/emmet/lib/editTree/css.js:580:49)
    at Object.gradientsFromCSSProperty (/packages/emmet/node_modules/emmet/lib/resolver/cssGradient.js:335:30)
    at Object.expandAbbreviationHandler (/packages/emmet/node_modules/emmet/lib/resolver/cssGradient.js:365:25)
    at /packages/emmet/node_modules/emmet/lib/assets/handlerList.js:93:19
    at /packages/emmet/node_modules/emmet/lib/utils/common.js:600:10
    at Array.some (native)
    at Object.find (/packages/emmet/node_modules/emmet/lib/utils/common.js:599:9)
    at HandlerList.exec (/packages/emmet/node_modules/emmet/lib/assets/handlerList.js:92:10)
    at Object.expandAbbreviationAction (/packages/emmet/node_modules/emmet/lib/action/expandAbbreviation.js:110:20)
    at Object.expandAbbreviationWithTabAction (/packages/emmet/node_modules/emmet/lib/action/expandAbbreviation.js:140:14)
    at Object.run (/packages/emmet/node_modules/emmet/lib/action/main.js:150:21)
    at Object.run (/packages/emmet/node_modules/emmet/lib/emmet.js:81:23)
    at runAction (/packages/emmet/lib/emmet.coffee:94:9)
    at /packages/emmet/lib/emmet.coffee:62:9
    at Object.exec (/packages/emmet/lib/editor-proxy.coffee:80:10)
    at /packages/emmet/lib/emmet.coffee:61:19
    at TextBuffer.module.exports.TextBuffer.transact (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/text-buffer/lib/text-buffer.js:952:24)
    at TextEditor.module.exports.TextEditor.transact (~/AppData/Local/atom/app-1.22.1/resources/app/src/text-editor.js:1687:32)
    at /packages/emmet/lib/emmet.coffee:60:24)
```

### Commands

```
     -8:31.8.0 emmet:expand-abbreviation-with-tab (input.hidden-input)
  4x -8:07.0 core:backspace (input.hidden-input)
  7x -8:01.4.0 emmet:expand-abbreviation-with-tab (input.hidden-input)
     -5:53.8.0 core:backspace (input.hidden-input)
     -5:45.3.0 core:save (input.hidden-input)
     -5:41.2.0 core:backspace (input.hidden-input)
     -5:31 core:save (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
     -4:49.6.0 core:backspace (input.hidden-input)
     -4:44 core:save (input.hidden-input)
     -4:24 emmet:expand-abbreviation-with-tab (input.hidden-input)
     -4:16.9.0 core:backspace (input.hidden-input)
     -4:12.5.0 core:save (input.hidden-input)
     -3:10.8.0 core:backspace (input.hidden-input)
     -3:08.5.0 core:save (input.hidden-input)
     -0:14.1.0 emmet:expand-abbreviation-with-tab (input.hidden-input)
```

### Non-Core Packages

```
emmet 2.4.3 
```

**Comment by lispwu** [comment]
atom throw this error once I hit "TAP"

**Comment by martinszeltins** [comment]
I have the exact same issue. When I press "tab" this error is thrown
