### ISSUE TITLE
Uncaught ParseError: CSS parsing error at line 4, char 1: Unterminated string    padding-left: 3...

### ISSUE THREAD

**Issue by jpjoshuapeter** [emmetio/emmet-atom#569]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.27.1 x64
**Electron**: 1.7.15
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [emmet](https://github.com/emmetio/emmet-atom) package 2.4.3

### Stack Trace

Uncaught ParseError: CSS parsing error at line 4, char 1: Unterminated string
    padding-left: 30px;
^

```
At C:\Users\jpjos\AppData\Local\atom\app-1.27.1\resources\app\node_modules\text-buffer\lib\text-buffer.js:980

ParseError: CSS parsing error at line 4, char 1: Unterminated string
    padding-left: 30px;
^
    at raiseError (/packages/emmet/node_modules/emmet/lib/parser/css.js:111:16)
    at eatString (/packages/emmet/node_modules/emmet/lib/parser/css.js:202:6)
    at str (/packages/emmet/node_modules/emmet/lib/parser/css.js:223:15)
    at tokenize (/packages/emmet/node_modules/emmet/lib/parser/css.js:336:11)
    at Object.lex (/packages/emmet/node_modules/emmet/lib/parser/css.js:389:6)
    at Object.parse (/packages/emmet/node_modules/emmet/lib/parser/css.js:407:22)
    at extractPropertiesFromSource (/packages/emmet/node_modules/emmet/lib/editTree/css.js:246:26)
    at consumeProperties (/packages/emmet/node_modules/emmet/lib/editTree/css.js:217:14)
    at child.initialize (/packages/emmet/node_modules/emmet/lib/editTree/css.js:316:4)
    at child.EditContainer (/packages/emmet/node_modules/emmet/lib/editTree/base.js:66:19)
    at /packages/emmet/node_modules/emmet/lib/vendor/klass.js:35:12)
    at Object.parse (/packages/emmet/node_modules/emmet/lib/editTree/css.js:550:11)
    at Object.parseFromPosition (/packages/emmet/node_modules/emmet/lib/editTree/css.js:566:16)
    at Object.propertyFromPosition (/packages/emmet/node_modules/emmet/lib/editTree/css.js:580:49)
    at Object.gradientsFromCSSProperty (/packages/emmet/node_modules/emmet/lib/resolver/cssGradient.js:335:30)
    at Object.expandAbbreviationHandler (/packages/emmet/node_modules/emmet/lib/resolver/cssGradient.js:365:25)
    at /packages/emmet/node_modules/emmet/lib/assets/handlerList.js:93:19
    at /packages/emmet/node_modules/emmet/lib/utils/common.js:600:10
    at Array.some (native)
    at Object.find (/packages/emmet/node_modules/emmet/lib/utils/common.js:599:9)
    at HandlerList.exec (/packages/emmet/node_modules/emmet/lib/assets/handlerList.js:92:10)
    at Object.expandAbbreviationAction (/packages/emmet/node_modules/emmet/lib/action/expandAbbreviation.js:110:20)
    at Object.expandAbbreviationWithTabAction (/packages/emmet/node_modules/emmet/lib/action/expandAbbreviation.js:140:14)
    at Object.run (/packages/emmet/node_modules/emmet/lib/action/main.js:150:21)
    at Object.run (/packages/emmet/node_modules/emmet/lib/emmet.js:81:23)
    at runAction (/packages/emmet/lib/emmet.coffee:94:9)
    at /packages/emmet/lib/emmet.coffee:62:9
    at Object.exec (/packages/emmet/lib/editor-proxy.coffee:80:10)
    at /packages/emmet/lib/emmet.coffee:61:19
    at TextBuffer.module.exports.TextBuffer.transact (~/AppData/Local/atom/app-1.27.1/resources/app/node_modules/text-buffer/lib/text-buffer.js:973:24)
```

### Commands

```
  8x -5:28.2.0 core:backspace (input.hidden-input)
     -5:11.1.0 core:delete (input.hidden-input)
  4x -5:07.0 core:backspace (input.hidden-input)
     -3:33.5.0 editor:newline (input.hidden-input)
     -3:32.7.0 core:delete (input.hidden-input)
 23x -3:26.7.0 core:backspace (input.hidden-input)
     -2:04.4.0 core:copy (input.hidden-input)
  7x -0:45.1.0 core:backspace (input.hidden-input)
     -0:42.1.0 editor:newline (input.hidden-input)
  7x -0:38.8.0 core:backspace (input.hidden-input)
     -0:35.6.0 emmet:expand-abbreviation-with-tab (input.hidden-input)
  2x -0:35 core:backspace (input.hidden-input)
     -0:33 emmet:expand-abbreviation-with-tab (input.hidden-input)
  7x -0:13.5.0 core:backspace (input.hidden-input)
     -0:10.2.0 emmet:expand-abbreviation-with-tab (input.hidden-input)
     -0:05.5.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused.autocomplete-active)
```

### Non-Core Packages

```
atom-runner 2.7.1 
autoclose-html 0.23.0 
autocomplete-python 1.10.5 
color-picker 2.3.0 
emmet 2.4.3 
ide-python 0.9.2 
kite 0.92.0 
pigments 0.40.2 
print-atom 0.1.1 
print-code 0.7.1 
```

**Comment by jpjoshuapeter** [comment]
Hitting tab to complete prompt is no longer working.
