### ISSUE TITLE
Uncaught ParseError: CSS parsing error at line 2, char 17: Unrecognized character '‬'  width: 84...

### ISSUE THREAD

**Issue by pchela9111** [emmetio/emmet-atom#608]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.0 x64
**Electron**: 3.1.10
**OS**: Unknown Windows version
**Thrown From**: [emmet](https://github.com/emmetio/emmet-atom) package 2.4.3

### Stack Trace

Uncaught ParseError: CSS parsing error at line 2, char 17: Unrecognized character '‬'
  width: 84.375%‬;
----------------^

```
At C:\Users\Elena Tkacheva\AppData\Local\atom\app-1.40.0\resources\app\static\<embedded>:11

ParseError: CSS parsing error at line 2, char 17: Unrecognized character '‬'
  width: 84.375%‬;
----------------^
    at raiseError (/packages/emmet/node_modules/emmet/lib/parser/css.js:111:16)
    at tokenize (/packages/emmet/node_modules/emmet/lib/parser/css.js:371:3)
    at Object.lex (/packages/emmet/node_modules/emmet/lib/parser/css.js:389:6)
    at Object.parse (/packages/emmet/node_modules/emmet/lib/parser/css.js:407:22)
    at extractPropertiesFromSource (/packages/emmet/node_modules/emmet/lib/editTree/css.js:246:26)
    at consumeProperties (/packages/emmet/node_modules/emmet/lib/editTree/css.js:217:14)
    at child.initialize (/packages/emmet/node_modules/emmet/lib/editTree/css.js:316:4)
    at child.EditContainer (/packages/emmet/node_modules/emmet/lib/editTree/base.js:66:19)
    at /packages/emmet/node_modules/emmet/lib/vendor/klass.js:35:12)
    at Object.parse (/packages/emmet/node_modules/emmet/lib/editTree/css.js:550:11)
    at Object.parseFromPosition (/packages/emmet/node_modules/emmet/lib/editTree/css.js:566:16)
    at Object.propertyFromPosition (/packages/emmet/node_modules/emmet/lib/editTree/css.js:580:49)
    at Object.gradientsFromCSSProperty (/packages/emmet/node_modules/emmet/lib/resolver/cssGradient.js:335:30)
    at Object.expandAbbreviationHandler (/packages/emmet/node_modules/emmet/lib/resolver/cssGradient.js:365:25)
    at /packages/emmet/node_modules/emmet/lib/assets/handlerList.js:93:19
    at /packages/emmet/node_modules/emmet/lib/utils/common.js:600:10
    at Array.some (<anonymous>)
    at Object.find (/packages/emmet/node_modules/emmet/lib/utils/common.js:599:9)
    at HandlerList.exec (/packages/emmet/node_modules/emmet/lib/assets/handlerList.js:92:10)
    at Object.expandAbbreviationAction (/packages/emmet/node_modules/emmet/lib/action/expandAbbreviation.js:110:20)
    at Object.expandAbbreviationWithTabAction (/packages/emmet/node_modules/emmet/lib/action/expandAbbreviation.js:140:14)
    at Object.run (/packages/emmet/node_modules/emmet/lib/action/main.js:150:21)
    at Object.run (/packages/emmet/node_modules/emmet/lib/emmet.js:81:23)
    at runAction (/packages/emmet/lib/emmet.coffee:94:9)
    at /packages/emmet/lib/emmet.coffee:62:9
    at Object.exec (/packages/emmet/lib/editor-proxy.coffee:80:10)
    at /packages/emmet/lib/emmet.coffee:61:19
    at TextBuffer.transact (~/AppData/Local/atom/app-1.40.0/resources/app/static/<embedded>:11:492111)
    at TextEditor.transact (~/AppData/Local/atom/app-1.40.0/resources/app/static/<embedded>:11:24215)
    at /packages/emmet/lib/emmet.coffee:60:24)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.40.0/resources/app/static/<embedded>:11:349123)
    at KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.40.0/resources/app/static/<embedded>:11:1249835)
    at KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.40.0/resources/app/static/<embedded>:11:1245969)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.40.0/resources/app/static/<embedded>:11:284329)
```

### Commands

```
     -0:08.6.0 emmet:expand-abbreviation-with-tab (input.hidden-input)
```

### Non-Core Packages

```
atom-alignment 0.13.0 
autoclose-html 0.23.0 
autocomplete-paths 2.12.2 
busy-signal 2.0.1 
color-picker 2.3.0 
double-tag 1.7.0 
editorconfig 2.5.0 
emmet 2.4.3 
file-icons 2.1.35 
highlight-selected 0.16.0 
intentions 1.1.5 
linter-ui-default 1.8.0 
multi-cursor 3.0.0 
open-in-browsers 0.0.30 
pigments 0.40.2 
svg-preview 0.14.0 
```

**Comment by pchela9111** [comment]
does not work reduction
