### ISSUE TITLE
Uncaught ParseError: CSS parsing error at line 2, char 1: Unrecognized character ' '   backgroun...

### ISSUE THREAD

**Issue by stormbornboy** [emmetio/emmet-atom#611]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [emmet](https://github.com/emmetio/emmet-atom) package 2.4.3

### Stack Trace

Uncaught ParseError: CSS parsing error at line 2, char 1: Unrecognized character ' '
   background: #11CDD4;
^

```
At C:\Users\Mg1\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11

ParseError: CSS parsing error at line 2, char 1: Unrecognized character ' '
   background: #11CDD4;
^
    at raiseError (/packages/emmet/node_modules/emmet/lib/parser/css.js:111:16)
    at tokenize (/packages/emmet/node_modules/emmet/lib/parser/css.js:371:3)
    at Object.lex (/packages/emmet/node_modules/emmet/lib/parser/css.js:389:6)
    at Object.parse (/packages/emmet/node_modules/emmet/lib/parser/css.js:407:22)
    at extractPropertiesFromSource (/packages/emmet/node_modules/emmet/lib/editTree/css.js:246:26)
    at consumeProperties (/packages/emmet/node_modules/emmet/lib/editTree/css.js:217:14)
    at child.initialize (/packages/emmet/node_modules/emmet/lib/editTree/css.js:316:4)
    at child.EditContainer (/packages/emmet/node_modules/emmet/lib/editTree/base.js:66:19)
    at /packages/emmet/node_modules/emmet/lib/vendor/klass.js:35:12)
    at Object.parse (/packages/emmet/node_modules/emmet/lib/editTree/css.js:550:11)
    at Object.parseFromPosition (/packages/emmet/node_modules/emmet/lib/editTree/css.js:566:16)
    at Object.propertyFromPosition (/packages/emmet/node_modules/emmet/lib/editTree/css.js:580:49)
    at Object.gradientsFromCSSProperty (/packages/emmet/node_modules/emmet/lib/resolver/cssGradient.js:335:30)
    at Object.expandAbbreviationHandler (/packages/emmet/node_modules/emmet/lib/resolver/cssGradient.js:365:25)
    at /packages/emmet/node_modules/emmet/lib/assets/handlerList.js:93:19
    at /packages/emmet/node_modules/emmet/lib/utils/common.js:600:10
    at Array.some (<anonymous>)
    at Object.find (/packages/emmet/node_modules/emmet/lib/utils/common.js:599:9)
    at HandlerList.exec (/packages/emmet/node_modules/emmet/lib/assets/handlerList.js:92:10)
    at Object.expandAbbreviationAction (/packages/emmet/node_modules/emmet/lib/action/expandAbbreviation.js:110:20)
    at Object.expandAbbreviationWithTabAction (/packages/emmet/node_modules/emmet/lib/action/expandAbbreviation.js:140:14)
    at Object.run (/packages/emmet/node_modules/emmet/lib/action/main.js:150:21)
    at Object.run (/packages/emmet/node_modules/emmet/lib/emmet.js:81:23)
    at runAction (/packages/emmet/lib/emmet.coffee:94:9)
    at /packages/emmet/lib/emmet.coffee:62:9
    at Object.exec (/packages/emmet/lib/editor-proxy.coffee:80:10)
    at /packages/emmet/lib/emmet.coffee:61:19
    at TextBuffer.transact (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:492395)
    at TextEditor.transact (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:24215)
    at /packages/emmet/lib/emmet.coffee:60:24)
```

### Commands

```
     -6:40 core:save (input.hidden-input)
     -6:08.8.0 core:move-up (input.hidden-input)
  4x -6:05.0 core:backspace (input.hidden-input)
  2x -5:54.4.0 core:move-down (input.hidden-input)
  2x -5:53.6.0 core:backspace (input.hidden-input)
     -5:33.1.0 emmet:expand-abbreviation-with-tab (input.hidden-input)
  4x -5:31.7.0 core:backspace (input.hidden-input)
 12x -5:25.1.0 emmet:expand-abbreviation-with-tab (input.hidden-input)
     -0:35.9.0 editor:newline (input.hidden-input)
     -0:31.3.0 core:backspace (input.hidden-input)
     -0:31.2.0 emmet:expand-abbreviation-with-tab (input.hidden-input)
     -0:10.6.0 core:move-up (input.hidden-input)
  5x -0:10.5.0 core:move-down (input.hidden-input)
     -0:08.8.0 autocomplete-plus:confirm (input.hidden-input)
     -0:08.7.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
     -0:00.1.0 autocomplete-plus:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-html-preview 0.2.6 
atom-ternjs 0.20.0 
autoclose 0.0.2 
busy-signal 2.0.1 
csslint 1.2.0 
emmet 2.4.3 
intentions 1.1.5 
language-ejs 0.4.0 
linter 2.3.1 
linter-eslint 8.5.5 
linter-jshint 3.1.17 
linter-ui-default 1.8.0 
pigments 0.40.2 
Sublime-Style-Column-Selection 1.7.5 
```

**Comment by stormbornboy** [comment]
can any body help me trough this?

**Comment by ArpadGBondor** [comment]
I had the same issue, and solved it with using beautify.
I probably copied a strange character into the CSS code, from this [button creator page](https://cssbuttoncreator.com/).

**Comment by AngelEyes311** [comment]
I used a button creator also...and then switched 'button' for 'navbar' and everytime i pressed tab after that inside the css brackets it red taped me lol gotta b that genertator i guess then lol
