### ISSUE TITLE
Installing “emmet@2.4.3” failed

### ISSUE THREAD

**Issue by mottorres** [emmetio/emmet-atom#620]
npm ERR! code Z_BUF_ERROR
npm ERR! errno -5
npm ERR! zlib: unexpected end of file

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\pc\.atom\.apm\_logs\2020-03-19T21_14_42_716Z-debug.log
[2020-03-19T21_14_42_716Z-debug.log](https://github.com/emmetio/emmet-atom/files/4356955/2020-03-19T21_14_42_716Z-debug.log)

**Comment by albeiroz** [comment]
I have this error to load the package of Emmet in Atom

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.15.4
**Thrown From**: [emmet](https://github.com/emmetio/emmet-atom) package 2.4.3


### Stack Trace

Failed to activate the emmet package

```
At Cannot find module 'emmet'

Error: Cannot find module 'emmet'
    at Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:155413)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146745)
    at /packages/emmet/lib/emmet.coffee:5:9)
    at /packages/emmet/lib/emmet.coffee:1:1)
    at /packages/emmet/lib/emmet.coffee:1:1)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147429)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:695134)
    at Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3233575)
    at Package.activateNow (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3221559)
    at measure (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3221337)
    at Package.measure (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3218947)
    at activationPromise.activationPromise.Promise (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3221197)
    at new Promise (<anonymous>)
    at Package.activate (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3221140)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:382452)
    at config.transactAsync (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:382068)
    at Config.transactAsync (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:331716)
    at PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:382018)
    at PackageManager.activate (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:381568)
    at t.loadState.then (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:717299)
```

### Commands

```
     -1:03.4.0 snippets:next-tab-stop (input.hidden-input)
     -1:03.4.0 snippets:expand (input.hidden-input)
     -1:03.4.0 editor:indent (input.hidden-input)
  3x -1:01.6.0 core:backspace (input.hidden-input)
     -0:52.7.0 emmet:interactive-expand-abbreviation (input.hidden-input)
```

### Non-Core Packages

```
atom-material-ui 2.1.3 
emmet 2.4.3 
emmet 2.4.3 
```
