### ISSUE TITLE
Uncaught ParseError: CSS parsing error at line 2, char 1: Unrecognized character ' '   -webkit-b...

### ISSUE THREAD

**Issue by WhismicalWallaby** [emmetio/emmet-atom#627]
[Enter steps to reproduce:]

1. I copied-pasted CSS code generated from https://cssbuttoncreator.com/
2. In the class for the button, I tried to add extra rules. However, when I tried indenting my line of code into the block, this error is thrown. I noticed in anywhere in the block of code for this class, hitting tab throws this error. Other characters do not cause issues.

**Atom**: 1.46.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.14.6
**Thrown From**: [emmet](https://github.com/emmetio/emmet-atom) package 2.4.3

### Stack Trace

Uncaught ParseError: CSS parsing error at line 2, char 1: Unrecognized character ' '
   -webkit-border-radius: 20px;
^

```
At /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11

ParseError: CSS parsing error at line 2, char 1: Unrecognized character ' '
   -webkit-border-radius: 20px;
^
    at raiseError (/packages/emmet/node_modules/emmet/lib/parser/css.js:111:16)
    at tokenize (/packages/emmet/node_modules/emmet/lib/parser/css.js:371:3)
    at Object.lex (/packages/emmet/node_modules/emmet/lib/parser/css.js:389:6)
    at Object.parse (/packages/emmet/node_modules/emmet/lib/parser/css.js:407:22)
    at extractPropertiesFromSource (/packages/emmet/node_modules/emmet/lib/editTree/css.js:246:26)
    at consumeProperties (/packages/emmet/node_modules/emmet/lib/editTree/css.js:217:14)
    at child.initialize (/packages/emmet/node_modules/emmet/lib/editTree/css.js:316:4)
    at child.EditContainer (/packages/emmet/node_modules/emmet/lib/editTree/base.js:66:19)
    at /packages/emmet/node_modules/emmet/lib/vendor/klass.js:35:12)
    at Object.parse (/packages/emmet/node_modules/emmet/lib/editTree/css.js:550:11)
    at Object.parseFromPosition (/packages/emmet/node_modules/emmet/lib/editTree/css.js:566:16)
    at Object.propertyFromPosition (/packages/emmet/node_modules/emmet/lib/editTree/css.js:580:49)
    at Object.gradientsFromCSSProperty (/packages/emmet/node_modules/emmet/lib/resolver/cssGradient.js:335:30)
    at Object.expandAbbreviationHandler (/packages/emmet/node_modules/emmet/lib/resolver/cssGradient.js:365:25)
    at /packages/emmet/node_modules/emmet/lib/assets/handlerList.js:93:19
    at /packages/emmet/node_modules/emmet/lib/utils/common.js:600:10
    at Array.some (<anonymous>)
    at Object.find (/packages/emmet/node_modules/emmet/lib/utils/common.js:599:9)
    at HandlerList.exec (/packages/emmet/node_modules/emmet/lib/assets/handlerList.js:92:10)
    at Object.expandAbbreviationAction (/packages/emmet/node_modules/emmet/lib/action/expandAbbreviation.js:110:20)
    at Object.expandAbbreviationWithTabAction (/packages/emmet/node_modules/emmet/lib/action/expandAbbreviation.js:140:14)
    at Object.run (/packages/emmet/node_modules/emmet/lib/action/main.js:150:21)
    at Object.run (/packages/emmet/node_modules/emmet/lib/emmet.js:81:23)
    at runAction (/packages/emmet/lib/emmet.coffee:94:9)
    at /packages/emmet/lib/emmet.coffee:62:9
    at Object.exec (/packages/emmet/lib/editor-proxy.coffee:80:10)
    at /packages/emmet/lib/emmet.coffee:61:19
    at TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:492516)
    at TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:24215)
    at /packages/emmet/lib/emmet.coffee:60:24)
```

### Commands

```
  3x -6:36.7.0 core:undo (input.hidden-input)
     -3:55.4.0 core:paste (input.hidden-input)
     -3:52.9.0 core:undo (input.hidden-input)
     -3:50.7.0 core:paste (input.hidden-input)
     -3:47 core:undo (input.hidden-input)
     -3:41.4.0 core:cut (input.hidden-input)
  2x -3:39.5.0 core:paste (input.hidden-input)
     -3:23.6.0 core:backspace (input.hidden-input)
     -3:21 core:cut (input.hidden-input)
     -3:19.8.0 core:backspace (input.hidden-input)
     -3:19.4.0 core:paste (input.hidden-input)
  2x -3:18.2.0 core:save (input.hidden-input)
  2x -0:31.4.0 editor:newline (input.hidden-input)
     -0:30.4.0 emmet:expand-abbreviation-with-tab (input.hidden-input)
     -0:04.8.0 core:backspace (input.hidden-input)
  3x -0:04.4.0 emmet:expand-abbreviation-with-tab (input.hidden-input)
```

### Non-Core Packages

```
atom-html-preview 0.2.6 
atom-ternjs 0.20.0 
autoclose 0.0.2 
csslint 1.2.0 
emmet 2.4.3 
language-ejs 0.4.0 
pigments 0.40.2 
```

**Comment by Bubble00** [comment]
This is issue can be resolved by removing a space at the begining of the line of code "-webkit-border-radius: 20px;"
