### ISSUE TITLE
download packages are'nt loading " Failed to load the emmet package"

### ISSUE THREAD

**Issue by SAbhi6** [emmetio/emmet-atom#651]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.57.0 ia32
**Electron**: 9.4.4
**OS**: Unknown Windows version
**Thrown From**: [emmet](https://github.com/emmetio/emmet-atom) package 2.4.3

### Stack Trace

Failed to load the emmet package

```
At Cannot find module 'emmet'
Require stack:
- C:\Users\karunakar\.atom\packages\emmet-atom-master\lib\emmet.coffee
- C:\Users\karunakar\AppData\Local\atom\app-1.57.0\resources\app.asar\static\index.html

Error: Cannot find module 'emmet'
Require stack:
- C:\Users\karunakar\.atom\packages\emmet-atom-master\lib\emmet.coffee
- C:\Users\karunakar\AppData\Local\atom\app-1.57.0\resources\app.asar\static\index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:797:17)
    at o._resolveFilename (electron/js2c/renderer_init.js:43:689)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:157820)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:149153)
    at /packages/emmet-atom-master/lib/emmet.coffee:5:9)
    at /packages/emmet-atom-master/lib/emmet.coffee:1:1)
    at /packages/emmet-atom-master/lib/emmet.coffee:1:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:149837)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:153385)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:74:18)
    at customRequire (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:1:802772)
    at requireModule (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:14:1191588)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:3520819)
    at ~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:3507359
    at Package.measure (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:3506159)
    at Package.load (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:3506932)
    at PackageManager.loadAvailablePackage (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:384071)
    at ~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:382494
    at Config.transact (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:334439)
    at PackageManager.loadPackages (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:382432)
    at ~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:1:823411
    at async Promise.all (index 0)
    at AtomEnvironment.startEditorWindow (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:1:825450)
```

### Commands

```
```

### Non-Core Packages

```
pigments 0.40.6 
autoclose-html-plus 0.27.2 
emmet 2.4.3 
```

**Comment by MacGuini** [comment]
Is there a fix for this?
